### ISSUE TITLE
The feature "QRSCANTEST" encountered an error when accessed in landscape mode

### ISSUE THREAD

**Issue by ahyar92** [v2ray/v2ray-core#1111]
#### Expected behavior
Supposedly, the "QRSCANTEST" feature works in landscape mode.

#### Actual behavior
When I use the "QRSCANTEST" feature in portrait mode, this feature works fine. However, different when I access the "QRSCANTEST" feature in landscape mode the feature suddenly encountered an error.

#### How to reproduce
1. Install and open the app
2. Next, go to the "Advanced" menu
3. Next access or open the feature "QRSCANTEST"  in landscape mode, then you will find the error as I experienced.

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 1.0 (Varies by device)

#### Recording Of The Bug
https://www.youtube.com/watch?v=EVmJHCJeeWI

#### Logcat
```--------- beginning of crash
05-19 00:22:58.360 13522 13522 E AndroidRuntime: FATAL EXCEPTION: main
05-19 00:22:58.360 13522 13522 E AndroidRuntime: Process: org.kkdev.v2raygo, PID: 13522
05-19 00:22:58.360 13522 13522 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kkdev.v2raygo/org.kkdev.andproj.libv2raycodescanner.BarcodeCaptureActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5527)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

05-19 00:22:58.360 13522 13522 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at org.kkdev.andproj.libv2raycodescanner.BarcodeCaptureActivity.onCreate(BarcodeCaptureActivity.java:96)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6303)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	... 9 more

05-19 00:22:58.360 13522 13522 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	... 17 more

05-19 00:22:58.360 13522 13522 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview" on path: DexPathList[[zip file "/data/app/org.kkdev.v2raygo-1/base.apk"],nativeLibraryDirectories=[/data/app/org.kkdev.v2raygo-1/lib/arm64, /data/app/org.kkdev.v2raygo-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:587)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	... 21 more

05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 		... 24 more
05-19 00:22:58.360 13522 13522 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by xiaokangwang** [comment]
This is a V2RayGO specific bug and this issue is being investigated in an low priority.

**Comment by DarienRaymond** [comment]
Moved to: https://github.com/xiaokangwang/V2RayGO/issues/9
