### ISSUE TITLE
自编译版无法运行

### ISSUE THREAD

**Issue by hutozh** [v2ray/v2ray-core#1123]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
自编译最新版
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
路由器
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
自编译无法运行，下载编译好的就可以。
4)  你期待看到的正确表现是怎样的？
自编译正常运行。
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
   {
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "error"
  },
  "inbound": {
    "port": 1234,
    "listen": "127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "auth": null,
      "udp": true,
      "ip": null,
      "clients": [
        {
          "id": "XXXX",
          "alterId": 100,
          "security": "none"
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true
      }
    }
  },
  "outbound": {
    "tag": null,
    "protocol": "freedom",
    "settings": null,
    "streamSettings": null,
    "mux": null
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": null,
      "tag": "blocked"
    }
  ],
  "dns": null,
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": null,
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "blocked",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}
```

    客户端配置:
```javascript
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "domainOverride": ["tls","http"],
    "port": 12345,
    "protocol": "dokodemo-door",
    "settings": {
	  "network": "tcp,udp",
      "followRedirect": true,
      "udp": true
    }
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "XXX.XXX.XXX",
          "port": 443,
          "users": [
            {
              "id": "XXXXXXXXX",
              "alterId": 100,
              "security": "chacha20-poly1305"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": "/",
        "headers": {
          "Host": "XXXXX"
        }
      }
    },
    "mux": {
      "enabled": true
    }
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```

    客户端错误日志:
```
Mon May 28 13:07:59 2018 daemon.info v2ray[3748]: V2Ray 3.24 (die Commanderin) Custom
Mon May 28 13:07:59 2018 daemon.info v2ray[3748]: A unified platform for anti-censorship.
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: panic: EOF
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]:
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: goroutine 1 [running]:
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: v2ray.com/core/common.Must(0x510c78, 0x10d0c038)
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: 	src/v2ray.com/core/common/common.go:10 +0x38
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: v2ray.com/core/common.Must2(0x30d800, 0x556ee0, 0x510c78, 0x10d0c038, 0x0, 0x510c78)
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: 	src/v2ray.com/core/common/common.go:16 +0x24
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: v2ray.com/core/common/buf.ReadAllToBytes(0x511050, 0x10d0c0d0, 0x187030, 0x0, 0xbe8e7eb4, 0x14, 0x10d58690)
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: 	src/v2ray.com/core/common/buf/multi_buffer.go:51 +0x10c
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: v2ray.com/core.loadProtobufConfig(0x511050, 0x10d0c0d0, 0xbe8e7ec6, 0x2, 0x10d586d8)
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: 	src/v2ray.com/core/config.go:72 +0x38
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: v2ray.com/core.LoadConfig(0x3651a9, 0x8, 0xbe8e7eb4, 0x14, 0x511050, 0x10d0c0d0, 0x0, 0x0, 0x2c0d88)
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: 	src/v2ray.com/core/config.go:59 +0x1d0
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: main.startV2Ray(0x0, 0x0, 0x0, 0x0)
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: 	src/v2ray.com/core/main/main.go:69 +0x214
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: main.main()
Mon May 28 13:07:59 2018 daemon.err v2ray[3748]: 	src/v2ray.com/core/main/main.go:105 +0x44
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
自编译使用的模块，上网方式为路由器透明代理，配置文件为pb。
```
	_ "v2ray.com/core/app/dispatcher"
	_ "v2ray.com/core/app/proxyman/inbound"
	_ "v2ray.com/core/app/proxyman/outbound"
	_ "v2ray.com/core/app/log"
	_ "v2ray.com/core/proxy/dokodemo"
	_ "v2ray.com/core/proxy/vmess/outbound"
	_ "v2ray.com/core/transport/internet/tls"
	_ "v2ray.com/core/transport/internet/websocket"
```

启动脚本为：
```
START=90

USE_PROCD=1

start_service() {
	mkdir /var/log/v2ray > /dev/null 2>&1
	procd_open_instance
	procd_set_param respawn
	procd_set_param command /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.pb -format=pb
	procd_set_param file /etc/v2ray/config.pb
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/v2ray.pid
	procd_close_instance
}
```
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by DarienRaymond** [comment]
你没有加载“从文件加载配置”的模块：

`_ "v2ray.com/core/main/confloader/external"`

在这种情况下，可以从stdin加载配置文件，命令行大约是这样的：

`/usr/bin/v2ray/v2ray -config=stdin: -format=pb < /etc/v2ray/config.pb`

**Comment by hutozh** [comment]
@DarienRaymond  使用命令/usr/bin/v2ray/v2ray -config=stdin: -format=pb < /etc/v2ray/config.pb依然提示错误，重新编译加入confloader模块后可以使用了。谢谢。
