### ISSUE TITLE
latest git HEAD panic

### ISSUE THREAD

**Issue by wongsyrone** [v2ray/v2ray-core#1266]
``` 
panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x962e72]

 goroutine 3044 [running]:
 v2ray.com/core/proxy/vmess/encoding.(*ClientSession).EncodeRequestHeader(0xc0003a6100, 0xc0008c4870, 0xbf2100, 0xc0009044e0, 0x0, 0x0)
 	E:/github/work/src/v2ray.com/core/proxy/vmess/encoding/client.go:74 +0xc2
 v2ray.com/core/proxy/vmess/outbound.(*Handler).Process.func2(0x0, 0x0)
 	E:/github/work/src/v2ray.com/core/proxy/vmess/outbound/outbound.go:120 +0x169
 v2ray.com/core/common/task.executeParallel.func1(0xc000363640, 0xc00039f1a0, 0xc00039f140)
 	E:/github/work/src/v2ray.com/core/common/task/task.go:162 +0x2b
 created by v2ray.com/core/common/task.executeParallel
 	E:/github/work/src/v2ray.com/core/common/task/task.go:161 +0xd7
```

**Comment by VictoriaRaymond** [comment]
在 3.41 里修了
