### ISSUE TITLE
Crash in test suite for 3.50.1 release

### ISSUE THREAD

**Issue by felixonmars** [v2ray/v2ray-core#1342]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
3.50.1

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Building a package for Arch Linux.

3) Please attach full panic log.
```
panic: Fail in goroutine after TestReverseProxy has completed
        panic: sync: negative WaitGroup counter

goroutine 413 [running]:
sync.(*WaitGroup).Add(0xc0017b0010, 0xffffffffffffffff)
        /usr/lib/go/src/sync/waitgroup.go:74 +0x137
sync.(*WaitGroup).Done(0xc0017b0010)
        /usr/lib/go/src/sync/waitgroup.go:99 +0x34
panic(0xd6f260, 0xc000254fe0)
        /usr/lib/go/src/runtime/panic.go:513 +0x1b9
testing.(*common).Fail(0xc003794100)
        /usr/lib/go/src/testing/testing.go:546 +0x135
testing.(*common).Error(0xc003794100, 0xc00022df88, 0x1, 0x1)
        /usr/lib/go/src/testing/testing.go:616 +0x6f
v2ray.com/core/testing/scenarios.TestReverseProxy.func1(0xc0017b0010, 0xb489, 0xc003794100)
        /build/v2ray/src/build/src/v2ray.com/core/testing/scenarios/reverse_test.go:209 +0x2e2
created by v2ray.com/core/testing/scenarios.TestReverseProxy
        /build/v2ray/src/build/src/v2ray.com/core/testing/scenarios/reverse_test.go:187 +0x13b3
```

**Comment by VictoriaRaymond** [comment]
Fixed in f3ad8acbe47dd5094765526a96ce72212e59aac4

In general, please don't use pre-releases for production. They are for testing only. In V2Ray all stable releases are labeled in the form 'x.y' like '3.50', while pre-releases are 'x.y.z'.
