### ISSUE TITLE
v2ray疑似有内存问题

### ISSUE THREAD

**Issue by hzlmy2002** [v2ray/v2ray-core#1493]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.9.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
浏览网页 ws+tls+nginx 之前一直好的
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
查看nginx的error.log发现nginx反代v2ray被connect refuse，更换v2ray的监听端口依然无效

2018/12/31 09:16:46 [error] 789#789: *54722 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: x, request: "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1", upstream: "http://127.0.0.1:10001/347070155b404dda9e3b4dbc65528671", host: "x"

------------------------------------------------------------------------------------------------------------------
Dec 31 10:26:40 x systemd[1]: Stopped V2Ray Service.
Dec 31 10:26:40 x systemd[1]: Started V2Ray Service.
Dec 31 10:26:40 x v2ray[1464]: V2Ray 4.9.0 (Po) 20181212
Dec 31 10:26:40 x v2ray[1464]: A unified platform for anti-censorship.
Dec 31 10:26:41 x v2ray[1464]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 31 10:26:41 x v2ray[1464]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x74480a]
Dec 31 10:26:41 x v2ray[1464]: goroutine 21 [running]:
Dec 31 10:26:41 x v2ray[1464]: v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000030740, 0xc05f40, 0xc00017aae0, 0xc00000b1c0, 0xc06
Dec 31 10:26:41 x v2ray[1464]:         v2ray.com/core/app/dispatcher/default.go:266 +0x6a
Dec 31 10:26:41 x v2ray[1464]: created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
Dec 31 10:26:41x v2ray[1464]:         v2ray.com/core/app/dispatcher/default.go:199 +0x215
Dec 31 10:26:41 x systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 31 10:26:41 x systemd[1]: v2ray.service: Failed with result 'exit-code'.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Dec 31 10:26:42x systemd[1]: Stopped V2Ray Service.
Dec 31 10:26:42 x systemd[1]: Started V2Ray Service.
Dec 31 10:26:42 x v2ray[1496]: V2Ray 4.9.0 (Po) 20181212
Dec 31 10:26:42 x v2ray[1496]: A unified platform for anti-censorship.
Dec 31 10:26:42 x v2ray[1496]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 31 10:26:42 x v2ray[1496]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x74480a]
Dec 31 10:26:42 x v2ray[1496]: goroutine 21 [running]:
Dec 31 10:26:42 x v2ray[1496]: v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000030780, 0xc05f40, 0xc000176ae0, 0xc00000b040, 0xc06900, 0xc00003260c, 0x300bf0035)
Dec 31 10:26:42 x v2ray[1496]:         v2ray.com/core/app/dispatcher/default.go:266 +0x6a
Dec 31 10:26:42 x v2ray[1496]: created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
Dec 31 10:26:42 x v2ray[1496]:         v2ray.com/core/app/dispatcher/default.go:199 +0x215
Dec 31 10:26:42 x systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 31 10:26:42x systemd[1]: v2ray.service: Failed with result 'exit-code'.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 6.
Dec 31 10:26:42 x systemd[1]: Stopped V2Ray Service.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Start request repeated too quickly.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Failed with result 'exit-code'.
Dec 31 10:26:42 x systemd[1]: Failed to start V2Ray Service.

以上现象在当天出现多次

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
更新会导致v2ray出错的陷阱配置

```javascript
  {
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "policy":{
    "levels":{
      "0":{
	"handshake":8,
	"connIdle":600,
	"uplinkOnly":2,
	"downlinkOnly":5,
	"statsUserUplink":false,
	"statsUserDownlink":false,
	"bufferSize":26214
          },
      "1":{
	"handshake":4,
	"connIdle":180,
	"uplinkOnly":2,
	"downlinkOnly":5,
	"statsUserUplink":false,
	"statsUserDownlink":false,
	"bufferSize":10240
          },
      "2":{
	"handshake":4,
	"connIdle":180,
	"uplinkOnly":2,
	"downlinkOnly":5,
	"statsUserUplink":false,
	"statsUserDownlink":false,
	"bufferSize":0
	  }
	     }
  },
  "inbounds": [
   {
    "port":10001,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "streamSettings":{
        "network":"ws",
        "wsSettings":{"path":"/347070155b404dda9e3b4dbc65528671"}
        },
    "settings": {
      "clients": [
        {
          "id": "a8470bc4-a6a1-4d43-939e-d586a2b35e7e",
          "level": 1,
          "alterId": 64
        },
	{
	 "id": "4b3aab56-6f38-4baa-865d-dcab0292101a",
	 "level": 0,
	 "alterId": 64
	},
	{
	 "id":"5311f0e5-8a8f-455e-adb4-461f7218d8ce",
	 "level":1,
	 "alterId":64
	},
	{
	 "id":"b313dfd3-bc06-46f4-89b1-acab5a1a5de7",
	 "level":2,
	 "alterId":64
	},
	{
	 "id":"15ab2c88-d5bb-4cf7-9dd2-f5401fbc6b1a",
	 "level":0,
	 "alterId":64
	},
	{
	 "id":"86ad60a8-19ba-4110-b27a-6ad0e343e372",
	 "level":2,
	 "alterId":64
	}
       ]
     }
    }
			  ]
		     }
   }
   ],
  "outbounds":[{
    "protocol": "freedom",
    "settings": {}
  }]
}
  
```
客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

2018/12/31 10:10:43 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:10:44 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:10:46 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:11:07 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:11:14 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:11:16 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:11:16 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:12:49 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:12:50 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:13:10 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:13:27 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:13:28 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:13:29 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:13:30 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:13:33 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:16:27 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:16:54 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:16:55 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:16:55 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:19:40 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:19:41 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:19:43 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:21:51 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10001: use of closed network connection
2018/12/31 10:22:03 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:26:35 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:26:39 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:26:40 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:26:41 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/31 10:26:42 [Warning] v2ray.com/core: V2Ray 4.9.0 started

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```
连接全部失败

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

2018/12/31 10:09:55 tcp:127.0.0.1:49698 accepted tcp:youtubei.googleapis.com:443
2018/12/31 10:09:56 tcp:127.0.0.1:49700 accepted tcp:www.googleapis.com:443
2018/12/31 10:10:17 tcp:127.0.0.1:49704 accepted tcp:redirector.googlevideo.com:443
2018/12/31 10:10:35 tcp:127.0.0.1:49708 accepted tcp:www.googleapis.com:443
2018/12/31 10:10:35 tcp:127.0.0.1:49710 accepted tcp:www.googleapis.com:443
2018/12/31 10:10:42 tcp:127.0.0.1:49714 accepted tcp:www.googleapis.com:443
2018/12/31 10:10:42 tcp:127.0.0.1:49714 accepted tcp:mtalk.google.com:5228
2018/12/31 10:10:44 tcp:127.0.0.1:49718 accepted tcp:www.googleapis.com:443
2018/12/31 10:10:46 tcp:127.0.0.1:49720 accepted tcp:www.googleapis.com:443
2018/12/31 10:11:07 tcp:127.0.0.1:49732 accepted tcp:play.googleapis.com:443
2018/12/31 10:11:07 tcp:127.0.0.1:49732 accepted tcp:www.googleapis.com:443
2018/12/31 10:11:14 tcp:127.0.0.1:49738 accepted tcp:play.googleapis.com:443
2018/12/31 10:11:15 tcp:127.0.0.1:49740 accepted tcp:t.appsflyer.com:443
2018/12/31 10:11:16 tcp:127.0.0.1:49742 accepted tcp:t.appsflyer.com:443
2018/12/31 10:12:48 tcp:127.0.0.1:49766 accepted tcp:www.googleadservices.com:443
2018/12/31 10:12:48 tcp:127.0.0.1:49766 accepted tcp:www.googleapis.com:443
2018/12/31 10:12:50 tcp:127.0.0.1:49768 accepted tcp:www.googleapis.com:443
2018/12/31 10:12:50 tcp:127.0.0.1:49768 accepted tcp:redirector.googlevideo.com:443
2018/12/31 10:13:10 tcp:127.0.0.1:49774 accepted tcp:play.googleapis.com:443
2018/12/31 10:13:27 tcp:127.0.0.1:49776 accepted tcp:www.googleapis.com:443
2018/12/31 10:13:27 tcp:127.0.0.1:49778 accepted tcp:www.googleapis.com:443
2018/12/31 10:13:28 tcp:127.0.0.1:49780 accepted tcp:www.googleapis.com:443
2018/12/31 10:13:30 tcp:127.0.0.1:49782 accepted tcp:www.googleapis.com:443
2018/12/31 10:13:32 tcp:127.0.0.1:49784 accepted tcp:www.googleapis.com:443
2018/12/31 10:13:34 tcp:127.0.0.1:49786 accepted tcp:yt3.ggpht.com:443
2018/12/31 10:16:53 127.0.0.1:37944 accepted tcp:toutyrater.github.io:443
2018/12/31 10:16:54 127.0.0.1:37946 accepted tcp:toutyrater.github.io:443
2018/12/31 10:16:55 127.0.0.1:37948 accepted tcp:toutyrater.github.io:443
2018/12/31 10:26:34 tcp:127.0.0.1:36432 accepted udp:9.9.9.9:53
2018/12/31 10:26:39 tcp:127.0.0.1:36438 accepted tcp:courier.push.apple.com:5223
2018/12/31 10:26:39 tcp:127.0.0.1:36440 accepted tcp:p31-buy.itunes.apple.com:443
2018/12/31 10:26:40 tcp:127.0.0.1:36442 accepted tcp:p31-buy.itunes.apple.com:443
2018/12/31 10:26:40 tcp:127.0.0.1:36442 accepted tcp:gspe1-ssl.ls.apple.com:443
2018/12/31 10:26:41 tcp:127.0.0.1:36444 accepted udp:9.9.9.9:53
2018/12/31 10:26:42 tcp:127.0.0.1:36446 accepted udp:9.9.9.9:53

8) 其它相关的配置文件（如 Nginx）和相关日志。
nginx access.log
x - - [31/Dec/2018:10:19:39 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 101 0 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:19:40 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 101 0 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:19:43 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 101 0 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:34 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 101 0 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:39 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 101 0 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:39 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 101 0 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:40 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 101 0 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:41 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 101 0 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:42 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 101 0 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:44 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:45 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:46 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:47 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:49 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:50 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:51 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:52 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:54 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:55 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:56 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:56 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:57 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:58 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:26:59 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:27:03 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:27:03 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:27:04 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:27:05 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:27:06 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
x - - [31/Dec/2018:10:27:10 +0800] "GET /347070155b404dda9e3b4dbc65528671 HTTP/1.1" 502 166 "-" "Go-http-client/1.1"
                                                                                                                                             

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

Dec 31 10:26:35 x systemd[1]: Started V2Ray Service.
Dec 31 10:26:35 x v2ray[1357]: V2Ray 4.9.0 (Po) 20181212
Dec 31 10:26:35 x v2ray[1357]: A unified platform for anti-censorship.
Dec 31 10:26:39 x v2ray[1357]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 31 10:26:39 x v2ray[1357]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x74480a]
Dec 31 10:26:39 x v2ray[1357]: goroutine 21 [running]:
Dec 31 10:26:39 x v2ray[1357]: v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000030740, 0xc05f40, 0xc000176ae0, 0xc00000b1e0, 0xc068c0, 0xc000063740, 0x200bf1467)
Dec 31 10:26:39 x v2ray[1357]:         v2ray.com/core/app/dispatcher/default.go:266 +0x6a
Dec 31 10:26:39 x v2ray[1357]: created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
Dec 31 10:26:39 x v2ray[1357]:         v2ray.com/core/app/dispatcher/default.go:199 +0x215
Dec 31 10:26:39 x systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 31 10:26:39 x systemd[1]: v2ray.service: Failed with result 'exit-code'.
Dec 31 10:26:39 x systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Dec 31 10:26:39 x systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
Dec 31 10:26:39 x systemd[1]: Stopped V2Ray Service.
Dec 31 10:26:39 x systemd[1]: Started V2Ray Service.
Dec 31 10:26:39 x v2ray[1400]: V2Ray 4.9.0 (Po) 20181212
Dec 31 10:26:39 x v2ray[1400]: A unified platform for anti-censorship.
Dec 31 10:26:39 x v2ray[1400]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 31 10:26:39 x v2ray[1400]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x74480a]
Dec 31 10:26:39 x v2ray[1400]: goroutine 21 [running]:
Dec 31 10:26:39 x v2ray[1400]: v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000030740, 0xc05f40, 0xc000178ae0, 0xc00000b1c0, 0xc068c0, 0xc000063740, 0x200bf01bb)
Dec 31 10:26:39 x v2ray[1400]:         v2ray.com/core/app/dispatcher/default.go:266 +0x6a
Dec 31 10:26:39 x v2ray[1400]: created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
Dec 31 10:26:39 x v2ray[1400]:         v2ray.com/core/app/dispatcher/default.go:199 +0x215
Dec 31 10:26:39 x systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 31 10:26:39 x systemd[1]: v2ray.service: Failed with result 'exit-code'.
Dec 31 10:26:40 x systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Dec 31 10:26:40 x systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 3.
Dec 31 10:26:40 x systemd[1]: Stopped V2Ray Service.
Dec 31 10:26:40 x systemd[1]: Started V2Ray Service.
Dec 31 10:26:40 x v2ray[1432]: V2Ray 4.9.0 (Po) 20181212
Dec 31 10:26:40 x v2ray[1432]: A unified platform for anti-censorship.
Dec 31 10:26:40 x v2ray[1432]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 31 10:26:40 x v2ray[1432]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x74480a]
Dec 31 10:26:40 x v2ray[1432]: goroutine 21 [running]:
Dec 31 10:26:40 x v2ray[1432]: v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000030740, 0xc05f40, 0xc000178ae0, 0xc00000b320, 0xc068c0, 0xc000063740, 0x200bf01bb)
Dec 31 10:26:40 x v2ray[1432]:         v2ray.com/core/app/dispatcher/default.go:266 +0x6a
Dec 31 10:26:40 x v2ray[1432]: created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
Dec 31 10:26:40 x v2ray[1432]:         v2ray.com/core/app/dispatcher/default.go:199 +0x215
Dec 31 10:26:40 x systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 31 10:26:40 x systemd[1]: v2ray.service: Failed with result 'exit-code'.
Dec 31 10:26:40 x systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Dec 31 10:26:40 x systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
Dec 31 10:26:40 x systemd[1]: Stopped V2Ray Service.
Dec 31 10:26:40 x systemd[1]: Started V2Ray Service.
Dec 31 10:26:40 x v2ray[1464]: V2Ray 4.9.0 (Po) 20181212
Dec 31 10:26:40 x v2ray[1464]: A unified platform for anti-censorship.
Dec 31 10:26:41 x v2ray[1464]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 31 10:26:41 x v2ray[1464]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x74480a]
Dec 31 10:26:41 x v2ray[1464]: goroutine 21 [running]:
Dec 31 10:26:41 x v2ray[1464]: v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000030740, 0xc05f40, 0xc00017aae0, 0xc00000b1c0, 0xc06900, 0xc00003260c, 0x300bf0035)
Dec 31 10:26:41 x v2ray[1464]:         v2ray.com/core/app/dispatcher/default.go:266 +0x6a
Dec 31 10:26:41 x v2ray[1464]: created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
Dec 31 10:26:41 x v2ray[1464]:         v2ray.com/core/app/dispatcher/default.go:199 +0x215
Dec 31 10:26:41 x systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 31 10:26:41 x systemd[1]: v2ray.service: Failed with result 'exit-code'.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Dec 31 10:26:42 x systemd[1]: Stopped V2Ray Service.
Dec 31 10:26:42 x systemd[1]: Started V2Ray Service.
Dec 31 10:26:42 x v2ray[1496]: V2Ray 4.9.0 (Po) 20181212
Dec 31 10:26:42 x v2ray[1496]: A unified platform for anti-censorship.
Dec 31 10:26:42 x v2ray[1496]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 31 10:26:42 x v2ray[1496]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x74480a]
Dec 31 10:26:42 x v2ray[1496]: goroutine 21 [running]:
Dec 31 10:26:42 x v2ray[1496]: v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000030780, 0xc05f40, 0xc000176ae0, 0xc00000b040, 0xc06900, 0xc00003260c, 0x300bf0035)
Dec 31 10:26:42 x v2ray[1496]:         v2ray.com/core/app/dispatcher/default.go:266 +0x6a
Dec 31 10:26:42 x v2ray[1496]: created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
Dec 31 10:26:42 x v2ray[1496]:         v2ray.com/core/app/dispatcher/default.go:199 +0x215
Dec 31 10:26:42 x systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 31 10:26:42 x systemd[1]: v2ray.service: Failed with result 'exit-code'.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 6.
Dec 31 10:26:42 x systemd[1]: Stopped V2Ray Service.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Start request repeated too quickly.
Dec 31 10:26:42 x systemd[1]: v2ray.service: Failed with result 'exit-code'.
Dec 31 10:26:42 x systemd[1]: Failed to start V2Ray Service.

vps内存正常
              total        used        free      shared  buff/cache   available
Mem:           1.9G        208M        1.3G        928K        403M        1.6G
Swap:          255M          0B        255M
请预览一下你填的内容再提交。

**Comment by hzlmy2002** [comment]
我知道原因了。配置文件有问题。但巧合的是配置文件的格式没问题。配置文件的问题阴差阳错的导致outbounds丢失，从而出现内存空指针。v2ray的test功能要完善。
