### ISSUE TITLE
访问一个错误网址的时候 v2ray panic(zero length segment)

### ISSUE THREAD

**Issue by fcying** [v2ray/v2ray-core#1638]
本来是用地址栏搜索一个问题的. 火狐没识别好. 直接当成网址传给v2ray了. 然后v2ray panic了.

地址栏搜索的内容
```
.linuxbrew/opt/curl/bin/curl: error while loading shared libraries: librtmp.so.0: cannot open shared object file: No such file or directory
```

v2ray log
```
2019/04/11 20:01:23 [Warning] v2ray.com/core: V2Ray 4.18.0 started
2019/04/11 20:01:26 [Info] [3058140603] v2ray.com/core/proxy/socks: TCP Connect request to tcp:.linuxbrew:80
2019/04/11 20:01:26 tcp:127.0.0.1:12868 accepted tcp:.linuxbrew:80 
```

panic log
```
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
panic: packing Question: Name: zero length segment

goroutine 38 [running]:
v2ray.com/core/common.Must(...)
        v2ray.com/core/common/common.go:17
v2ray.com/core/app/dns.(*ClassicNameServer).sendQuery(0xc0001b2500, 0xd03ee0, 0xc00040a1b0, 0xc0003976f0, 0xb, 0x101)
        v2ray.com/core/app/dns/udpns.go:371 +0x41f
v2ray.com/core/app/dns.(*ClassicNameServer).QueryIP(0xc0001b2500, 0xd03ee0, 0xc00040a1b0, 0xc0003a2032, 0xa, 0xc000430101, 0x0, 0x0, 0x0, 0x0, ...)
        v2ray.com/core/app/dns/udpns.go:439 +0x1e4
v2ray.com/core/app/dns.(*Server).queryIPTimeout(0xc00038e150, 0xcfdce0, 0xc0001b2500, 0xc0003a2032, 0xa, 0x101, 0x0, 0xc0003e3fe0, 0xc0002669d0, 0xc0003e34a0, ...)
        v2ray.com/core/app/dns/server.go:145 +0xdc
v2ray.com/core/app/dns.(*Server).lookupIPInternal(0xc00038e150, 0xc0003a2032, 0xa, 0xc000140101, 0x5a5fac, 0xc0003a2032, 0xa, 0xc0003a2032, 0xa)
        v2ray.com/core/app/dns/server.go:240 +0x247
v2ray.com/core/app/dns.(*Server).LookupIP(0xc00038e150, 0xc0003a2032, 0xa, 0x40371a, 0xcf1878, 0xcf1880, 0xc0003faa01, 0xc00043c670)
        v2ray.com/core/app/dns/server.go:152 +0x4d
v2ray.com/core/app/router.(*Context).GetTargetIPs(0xc00040a030, 0xcf1898, 0xcee25b, 0x3989368)
        v2ray.com/core/app/router/router.go:161 +0x12d
v2ray.com/core/app/router.getIPsFromTarget(0xc00040a030, 0xc000165d58, 0x40bbc9, 0xc00040a030)
        v2ray.com/core/app/router/condition.go:112 +0x32
v2ray.com/core/app/router.(*MultiGeoIPMatcher).Apply(0xc000149800, 0xc00040a030, 0xb4c180)
        v2ray.com/core/app/router/condition.go:144 +0x45
v2ray.com/core/app/router.(*ConditionChan).Apply(0xc0001497c0, 0xc00040a030, 0xc00040a030)
        v2ray.com/core/app/router/condition.go:33 +0x76
v2ray.com/core/app/router.(*Rule).Apply(0xc000150030, 0xc00040a030, 0xc0003bc040)
        v2ray.com/core/app/router/config.go:63 +0x45
v2ray.com/core/app/router.(*Router).pickRouteInternal(0xc00038d4c0, 0xd03ee0, 0xc0004422a0, 0xc000445600, 0xc0003faf50, 0xc000409d00)
        v2ray.com/core/app/router/router.go:102 +0x15c
v2ray.com/core/app/router.(*Router).PickRoute(0xc00038d4c0, 0xd03ee0, 0xc0004422a0, 0xc00014aca0, 0xc0003e5910, 0xc000444500, 0xc000445a70)
        v2ray.com/core/app/router/router.go:78 +0x4a
v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc00014c240, 0xd03ee0, 0xc0004422a0, 0xc000446360, 0xd04ea0, 0xc000444060, 0x200400050)
        v2ray.com/core/app/dispatcher/default.go:261 +0x2a5
created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
        v2ray.com/core/app/dispatcher/default.go:205 +0x20a
```

**Comment by kslr** [comment]
当关闭代理时进入搜索 https://www.google.com/search?client=firefox-b-d&q=.linuxbrew
当使用DoH时 (cloudflare) 进入 www..linuxbrew

**Comment by xiaokangwang** [comment]
这个问题在于V2Ray在收到错误的请求的时候应该返回错误信息，而不是崩溃。

我感觉这个确实算作是一个bug。

**Comment by fcying** [comment]
整了半天 还是没搭好编译环境....等release了@_@

设了GOCACHE就没用....最后命令行出来还是`GOCACHE=@D`

```
bazel build --action_env=GOPATH=$GOPATH --action_env=GOCACHE=/home/fcying/.cache/go-build --action_env=PATH=$PATH //release:v2ray_windows_amd64_package --sandbox_debug
INFO: Analysed target //release:v2ray_windows_amd64_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/fcying/go/src/github.com/v2ray/v2ray-core/infra/control/main/BUILD:8:1: error executing shell command: '/bin/bash -c CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOROOT_FINAL=/go GOCACHE=@D go build -o bazel-out/k8-fastbuild/bin/infra/control/main/windows/amd64/v2ctl.exe -compiler gc -gcflags "all=-trimpa...' failed (Exit 1) process-wrapper failed: error executing command 
  (cd /home/fcying/.cache/bazel/_bazel_fcying/c703a6b9ddeab159c72fe2921524d6b1/sandbox/processwrapper-sandbox/2/execroot/v2ray_core && \
  exec env - \
    GOCACHE=/home/fcying/.cache/go-build \
    GOPATH=/home/fcying/go \
    PATH=/home/fcying/bin:/home/fcying/.local/bin:/home/fcying/tool/go/bin:/home/fcying/qt/5.12.1/gcc_64/bin:/home/fcying/go/bin:/home/fcying/.cargo/bin:/snap/bin:/home/fcying/.yarn/bin:/home/fcying/.config/yarn/global/node_modules/.bin:/home/fcying/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/fcying/.fzf/bin \
    TMPDIR=/tmp \
  /home/fcying/.cache/bazel/_bazel_fcying/install/7da6a92c096ada842b8d48c251312343/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOROOT_FINAL=/go GOCACHE=@D go build -o bazel-out/k8-fastbuild/bin/infra/control/main/windows/amd64/v2ctl.exe -compiler gc -gcflags "all=-trimpath=${GOPATH}/src" -asmflags "all=-trimpath=${GOPATH}/src" -ldflags '\''-s -w'\'' -tags '\''confonly'\'' v2ray.com/core/infra/control/main')
build cache is required, but could not be located: GOCACHE is not an absolute path
Target //release:v2ray_windows_amd64_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.277s, Critical Path: 0.16s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by 1265578519** [comment]
v4.18.1说已修复

**Comment by aybru** [comment]
最近v2停更了吗？

**Comment by kslr** [comment]
@aybru 没有
