### ISSUE TITLE
dokodemo-door runtime error

### ISSUE THREAD

**Issue by soffchen** [v2ray/v2ray-core#172]
```
{
  "log": {
    "loglevel": "warning"
  },
  "dokodemo-door": {
    "port": 10801,
    "address": "",
    "network": "tcp",
    "timeout": 0,
    "followRedirect": true
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "xxxxxx",
          "port": 10086,
          "users": [
            {
              "id": "41372105-f2e0-4ec8-9cd7-f7b25106889a",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
}
```

运行报错

```
V2Ray v1.16 (New Order) 20160612
An unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x48ee5f]

goroutine 1 [running]:
panic(0x8c3680, 0xc82000e0e0)
	/home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:481 +0x3e6
github.com/v2ray/v2ray-core/shell/point.NewPoint(0xc8205783f0, 0xa, 0x0, 0x0)
	/home/travis/gopath/src/github.com/v2ray/v2ray-core/shell/point/point.go:38 +0x5f
main.main()
	/home/travis/gopath/src/github.com/v2ray/v2ray-core/release/server/main.go:79 +0x84d
```

**Comment by v2ray** [comment]
正确的写法如下，注意 dokodemo-door 部分的改动。

```javascript
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 10801,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "",
      "network": "tcp",
      "timeout": 0,
      "followRedirect": true
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "xxxxxx",
          "port": 10086,
          "users": [
            {
              "id": "41372105-f2e0-4ec8-9cd7-f7b25106889a",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
}
```

**Comment by soffchen** [comment]
啊，明白了，原来是我写错了，愚钝了

感谢
