### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by htfy96** [v2ray/v2ray-core#176]
Log:
```
V2Ray v1.16 (New Order) 20160612
An unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4b2bd3]

goroutine 7138 [running]:
panic(0x8c3680, 0xc820012080)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:481 +0x3e6
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).GetUser(0xc820d422a0, 0x0, 0x0, 0x801a80)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/inbound.go:99 +0x73
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).generateCommand(0xc820581c80, 0xc821293b60, 0x0, 0x0)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/command.go:20 +0x3e8
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).HandleConnection(0xc820581c80, 0xc8211f7980)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/inbound.go:184 +0xf73
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).HandleConnection-fm(0xc8211f7980)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/inbound.go:109 +0x2a
created by github.com/v2ray/v2ray-core/transport/hub.(*TCPHub).start
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/transport/hub/tcp.go:71 +0x359
```

Config: 
```
vmess_main -> vmess_random_port(6000, 7000)
shadowsocks
```

**Comment by v2ray** [comment]
能否贴一下你的配置文件，看上去像是配置文件有问题。（当然 panic 也是不对的）

**Comment by htfy96** [comment]
```
{
    "port": 21217,
    "log" : {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "______",
                    "level": 1,
                    "alterId": 64
                }
            ],
            "features": {
                "detour": {
                    "to": "detour"
                }
            }
        }
    },  
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },  
    "inboundDetour": [
        {
            "protocol": "vmess",
            "port": "2700-2800", 
            "tag": "detour",
            "settings": {},
            "allocate": {  
                "strategy": "random",
                "concurrency": 5,   
                "refresh": 5       
            }
        },
        {
            "protocol": "shadowsocks",
            "port": 3001,
            "settings": {
                "method": "aes-256-cfb",
                "password": "_______",   
                "udp": true
            }
        }
    ],  
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],  
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }   
}   
```

**Comment by htfy96** [comment]
又崩溃了两次
```
V2Ray v1.16 (New Order) 20160612
An unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4b2bd3]

goroutine 3164 [running]:
panic(0x8c3680, 0xc820012080)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:481 +0x3e6
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).GetUser(0xc8209adf80, 0x0, 0x0, 0x801a80)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/inbound.go:99 +0x73
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).generateCommand(0xc82057dce0, 0xc8208c5470, 0x0, 0x0)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/command.go:20 +0x3e8
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).HandleConnection(0xc82057dce0, 0xc82071edc0)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/inbound.go:184 +0xf73
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).HandleConnection-fm(0xc82071edc0)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/inbound.go:109 +0x2a
created by github.com/v2ray/v2ray-core/transport/hub.(*TCPHub).start
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/transport/hub/tcp.go:71 +0x359
V2Ray v1.16 (New Order) 20160612
An unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4b2bd3]

goroutine 933 [running]:
panic(0x8c3680, 0xc820012080)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:481 +0x3e6
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).GetUser(0xc820b785a0, 0x0, 0x0, 0x801a80)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/inbound.go:99 +0x73
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).generateCommand(0xc8205f0a80, 0xc820b2e870, 0x0, 0x0)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/command.go:20 +0x3e8
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).HandleConnection(0xc8205f0a80, 0xc82059f480)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/inbound.go:184 +0xf73
github.com/v2ray/v2ray-core/proxy/vmess/inbound.(*VMessInboundHandler).HandleConnection-fm(0xc82059f480)
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/vmess/inbound/inbound.go:109 +0x2a
created by github.com/v2ray/v2ray-core/transport/hub.(*TCPHub).start
        /home/travis/gopath/src/github.com/v2ray/v2ray-core/transport/hub/tcp.go:71 +0x359
```

error.log:
```
2016/06/18 04:05:14 [Error]Point: Failed to refresh dynamic allocations: listen tcp 0.0.0.0:2722: bind: address already in use
2016/06/18 04:11:37 [Warning]VMessIn: Invalid request from 59.78.45.192:35022: Invalid user.
2016/06/18 04:29:14 [Error]Unable to listen tcp 0.0.0.0:2730: listen tcp 0.0.0.0:2730: bind: address already in use
2016/06/18 04:29:14 [Error]Point: Failed to start inbound connection handler: listen tcp 0.0.0.0:2730: bind: address already in use
2016/06/18 04:29:14 [Error]Point: Failed to refresh dynamic allocations: listen tcp 0.0.0.0:2730: bind: address already in use
2016/06/18 04:47:14 [Error]Unable to listen tcp 0.0.0.0:2788: listen tcp 0.0.0.0:2788: bind: address already in use
2016/06/18 04:47:14 [Error]Point: Failed to start inbound connection handler: listen tcp 0.0.0.0:2788: bind: address already in use
2016/06/18 04:47:14 [Error]Point: Failed to refresh dynamic allocations: listen tcp 0.0.0.0:2788: bind: address already in use
2016/06/18 04:53:14 [Error]Unable to listen tcp 0.0.0.0:2783: listen tcp 0.0.0.0:2783: bind: address already in use
2016/06/18 04:53:14 [Error]Point: Failed to start inbound connection handler: listen tcp 0.0.0.0:2783: bind: address already in use
2016/06/18 04:53:14 [Error]Point: Failed to refresh dynamic allocations: listen tcp 0.0.0.0:2783: bind: address already in use # 第一次崩溃
2016/06/18 05:26:00 [Warning]Point: started on port 21217
2016/06/18 05:55:00 [Error]Unable to listen tcp 0.0.0.0:2724: listen tcp 0.0.0.0:2724: bind: address already in use
2016/06/18 05:55:00 [Error]Point: Failed to start inbound connection handler: listen tcp 0.0.0.0:2724: bind: address already in use
2016/06/18 05:55:00 [Error]Point: Failed to refresh dynamic allocations: listen tcp 0.0.0.0:2724: bind: address already in use
2016/06/18 06:01:00 [Error]Unable to listen tcp 0.0.0.0:2737: listen tcp 0.0.0.0:2737: bind: address already in use
2016/06/18 06:01:00 [Error]Point: Failed to start inbound connection handler: listen tcp 0.0.0.0:2737: bind: address already in use
2016/06/18 06:01:00 [Error]Point: Failed to refresh dynamic allocations: listen tcp 0.0.0.0:2737: bind: address already in use # 第二次崩溃
2016/06/18 06:02:17 [Warning]Point: started on port 21217
```

**Comment by v2ray** [comment]
会在下个版本中修复

**Comment by v2ray** [comment]
应该已经修复了
