### ISSUE TITLE
server panic: runtime error: invalid memory address or nil pointer dereference on shadowsocks protocol, websocket transportation

### ISSUE THREAD

**Issue by peter-tank** [v2ray/v2ray-core#1853]
- Cross compiled for linux amd64 from aarch64 android termux.
  - `go version`
  > go version go1.12.7 android/arm64

  - V2Ray 4.20.0 (user) 20190716-173952
A unified platform for anti-censorship.

  - client: shadowsocks outbound, websocket transportation, method: chacha20-ietf

  - server panic
  > panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9f373a]
  > goroutine 71791 [running]:
v2ray.com/core/proxy/shadowsocks.(*Server).handleConnection(0xc0002b0d80, 0xdd0340, 0xc000f04480, 0xdd7980, 0xc000f044b0, 0xdd0f40, 0xc0001f65a0, 0x30, 0xc6b300)
  > /data/data/com.termux/files/home/golang/src/v2ray.com/core/proxy/shadowsocks/server.go:167 +0x2ba
v2ray.com/core/proxy/shadowsocks.(*Server).Process(0xc0002b0d80, 0xdd0340, 0xc000f04480, 0x2, 0xdd7980, 0xc000f044b0, 0xdd0f40, 0xc0001f65a0, 0x7f1b0f459008, 0x408a1c)
  > /data/data/com.termux/files/home/golang/src/v2ray.com/core/proxy/shadowsocks/server.go:66 +0x255
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).callback(0xc0000ed7a0, 0xdd7980, 0xc000f044b0)
  > /data/data/com.termux/files/home/golang/src/v2ray.com/core/app/proxyman/inbound/worker.go:97 +0x47b
created by v2ray.com/core/app/proxyman/inbound.(*tcpWorker).Start.func1
	  > /data/data/com.termux/files/home/golang/src/v2ray.com/core/app/proxyman/inbound/worker.go:113 +0x52

**Comment by peter-tank** [comment]
Not reproducible on recent builds(20190909) for days, assumming fixed by: [MODs in: shadowsocks.(*Server).handleConnection _nil_read_on_IV_](https://github.com/v2ray/v2ray-core/commit/5ab4f5ab9a1e60aff4d22a3b837569e3c3e2747d)
  >rejected  v2ray.com/core/proxy/shadowsocks: failed to read IV > websocket: close 1006 (abnormal closure): unexpected EOF
  >rejected  v2ray.com/core/proxy/shadowsocks: failed to read IV > read tcp 127.0.0.1:xxxx->172.xx.xx.xxx:37972: i/o timeout
