### ISSUE TITLE
Windows 服务器会在运行一段时间后自动关闭

### ISSUE THREAD

**Issue by DeepAQ** [v2ray/v2ray-core#192]
如题，服务器环境是 Windows Server 2008 R2 ，客户端有 Shadowsocks 也有 VMess 。每次运行 v2ray 后一段时间就会自动关闭，此时在 access.log 和 error.log 中均出现乱码信息如下：

2016/07/04 20:42:06 xxx.xxx.xxx.4:60878 accepted tcp:?顇?剰??邖)镔?祴&骓緃閑lu?矌宆?鑁s/豄湰錌?H|宴???o返坚翘$捎瓮蛰攫鵓?39641 

2016/07/04 20:42:07 [Warning]Freedom: Failed to open connection to tcp:?顇?剰??邖)镔?祴&骓緃閑lu?矌宆?鑁s/豄湰錌?H|宴???o返坚翘$捎瓮蛰攫鵓?39641: All retry attempts failed.

**Comment by DeepAQ** [comment]
贴一下服务器的 config.json :

{
    "port": xxxx,
    "log": {
        "access": "access.log",
        "error": "error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "xxxxxxxxxx",
                    "level": 1
                }
            ]
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {
            "domainStrategy": "AsIs",
            "timeout": 0
        }
    },
    "inboundDetour": [
        {
            "port": xxxx,
            "protocol": "shadowsocks",
            "settings": {
                "method": "chacha20",
                "password": "xxxxxxxxxx",
                "udp": true,
                "level": 1
            }
        }
    ],
    "outboundDetour": []
}

**Comment by DeepAQ** [comment]
终于能看到完整的错误信息了：

panic: syscall: string with NUL passed to StringToUTF16

goroutine 4286 [running]:
panic(0x81c880, 0xc082624300)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:481 +0x3f4
syscall.StringToUTF16(0xc08200e630, 0x83, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/syscall/syscall_windows.go:31 +0xdd
syscall.StringToUTF16Ptr(0xc08200e630, 0x83, 0xc0829a9c68)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/syscall/syscall_windows.go:66 +0x32
net.newLookupIP(0xc08200e630, 0x83, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/net/lookup_windows.go:118 +0x124
net.glob.func15(0xa5c798, 0xc08200e630, 0x83, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/net/hook.go:10 +0x54
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/net/lookup.go:106 +0x78
internal/singleflight.(*Group).doCall(0xc0c2c0, 0xc08200c1e0, 0xc08200e630, 0x83, 0xc08358e440)
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/internal/singleflight/singleflight.go:93 +0x33
created by internal/singleflight.(*Group).DoChan
        /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/internal/singleflight/singleflight.go:86 +0x3f5

**Comment by DeepAQ** [comment]
1.19 貌似已经没有这个问题了
