### ISSUE TITLE
V2Ray 在使用 DoH 解析带有 @ 或 . 开头的域名时会导致 SEGFAULT

### ISSUE THREAD

**Issue by Qv2ray-dev** [v2ray/v2ray-core#2599]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 4.23.1 ~ V2Ray 4.25.0 @ Linux amd64, Windows amd64
4.23.1 以下版本未经测试
如下所示，此问题出现在链接服务器之前，故不需要服务器，仅一个直连出站即可复现

2) 你的使用场景是什么?
使用 curl 配合 v2ray 下载

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

核心崩溃退出

- freedom 出站域名需要在 Freedom 出站中设置 `"domainStrategy": "UseIP"`
`curl -x socks5h://localhost:1080/ https://.baidu.com`
`curl -x socks5h://localhost:1080/ https://@.baidu.com`
`curl -x socks5h://localhost:1080/ https://prefix.@.baidu.com`

- 其它域名复现需要在路由中使用 `IpIfNonMatch`
`curl -x socks5h://localhost:1080/ https://.google.com`
`curl -x socks5h://localhost:1080/ https://@.google.com`
`curl -x socks5h://localhost:1080/ https://prefix.@.google.com`

4) 你期待看到的正确表现是怎样的？
不崩溃

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

客户端配置: （已打码）

<details>

```
{
    "api": {
        "services": [
            "HandlerService",
            "LoggerService",
            "StatsService"
        ],
        "tag": "_QV2RAY_API_"
    },
    "dns": {
        "servers": [
            "https://1.1.1.1/dns-query"
        ]
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 11541,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "sniffing": {
            },
            "tag": "_QV2RAY_API_INBOUND_"
        },
        {
            "listen": "127.0.0.1",
            "port": 8001,
            "protocol": "http",
            "settings": {
            },
            "sniffing": {
                "enabled": false
            },
            "tag": "http_IN"
        },
        {
            "listen": "127.0.0.1",
            "port": 1080,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "ip": "127.0.0.1",
                "udp": true,
                "userLevel": 0
            },
            "sniffing": {
                "destOverride": [
                    "http",
                    "tls"
                ],
                "enabled": true
            },
            "tag": "socks_IN"
        }
    ],
    "log": {
        "loglevel": "warning"
    },
    "outbounds": [
        {
            "mux": {
            },
            "protocol": "socks",
            "sendThrough": "0.0.0.0",
            "settings": {
                "servers": [
                    {
                        "address": "127.0.0.1",
                        "port": 15000
                    }
                ]
            },
            "streamSettings": {
            },
            "tag": "outBound_PROXY"
        },
        {
            "mux": {
            },
            "protocol": "freedom",
            "sendThrough": "0.0.0.0",
            "settings": {
                "domainStrategy": "UseIP",
                "redirect": ":0",
                "userLevel": 0
            },
            "streamSettings": {
            },
            "tag": "outBound_DIRECT"
        },
        {
            "mux": {
            },
            "protocol": "blackhole",
            "sendThrough": "0.0.0.0",
            "settings": {
                "response": {
                    "type": "none"
                }
            },
            "streamSettings": {
            },
            "tag": "outBound_BLACKHOLE"
        }
    ],
    "policy": {
        "system": {
            "statsInboundDownlink": true,
            "statsInboundUplink": true
        }
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "inboundTag": [
                    "_QV2RAY_API_INBOUND_"
                ],
                "outboundTag": "_QV2RAY_API_",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:github"
                ],
                "outboundTag": "outBound_PROXY",
                "type": "field"
            },
            {
                "domain": [
                    "domain:mole.61.com"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "outBound_DIRECT",
                "type": "field"
            }
        ]
    },
    "stats": {
    }
}

```

</details>

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

客户端错误日志:
```
2020/06/25 11:35:02 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain .baidu.com at server UDP:1.1.1.1:53 > context deadline exceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55f43b5f1b9f]

goroutine 90 [running]:
v2ray.com/core/common/buf.(*Buffer).Bytes(...)
        v2ray.com/core/common/buf/buffer.go:54
v2ray.com/core/app/dns.(*DoHNameServer).sendQuery.func1(0x55f43baa3c00, 0xc0000c0240, 0xc0004bcd60, 0xc000541880, 0xc00053afa0)
        v2ray.com/core/app/dns/dohdns.go:250 +0x20f
created by v2ray.com/core/app/dns.(*DoHNameServer).sendQuery
        v2ray.com/core/app/dns/dohdns.go:227 +0x323
```

![image](https://user-images.githubusercontent.com/59914293/85657252-61554b80-b6e4-11ea-832e-c8dc68b56f31.png)

**Comment by DuckSoft** [comment]
Reproduced on Arch Linux 5.7.4, V2Ray 4.25.0 (v2fly, go1.14.4 linux/amd64).

**Comment by xiaokangwang** [comment]
I would like request author of DoH to investigate this first. @vcptr

**Comment by DuckSoft** [comment]
打了我这个补丁之后就不闪退了，但是具体 dns.PackMessage 里面有没有别的坑，还是需要原作者调查一下。

```patch
diff --git a/app/dns/dohdns.go b/app/dns/dohdns.go
index 89f96df8..1e08c4cb 100644
--- a/app/dns/dohdns.go
+++ b/app/dns/dohdns.go
@@ -246,7 +246,11 @@ func (s *DoHNameServer) sendQuery(ctx context.Context, domain string, option IPO
 			dnsCtx, cancel := context.WithDeadline(dnsCtx, deadline)
 			defer cancel()
 
-			b, _ := dns.PackMessage(r.msg)
+			b, err := dns.PackMessage(r.msg)
+			if err != nil {
+				newError("failed to pack dns query").Base(err).AtError().WriteToLog()
+				return
+			}
 			resp, err := s.dohHTTPSContext(dnsCtx, b.Bytes())
 			if err != nil {
 				newError("failed to retrive response").Base(err).AtError().WriteToLog()
```

**Comment by darhwa** [comment]
像这种涉及到状态机的代码，是否可以考虑引入fuzzing测试？
