### ISSUE TITLE
failed to start v2ray service on a transit server

### ISSUE THREAD

**Issue by Jirache321** [v2ray/v2ray-core#2637]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
V2Ray 4.26.0
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Transit via a CN-based ip(which has a problem) to a vpn locate outside
3) Please attach full panic log.
```
# ./v2ray -test -config config.json
V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)
A unified platform for anti-censorship.
main: failed to read config files: [config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  config.json
panic: open config.json: no such file or directory

goroutine 1 [running]:
v2ray.com/core/common.Must(...)
	v2ray.com/core/common/common.go:17
v2ray.com/core/infra/control.(*ConfigCommand).Execute(0xfbd350, 0xc0000301a0, 0x1, 0x1, 0xc00018e528, 0xbda5e1ede89e3e01)
	v2ray.com/core/infra/control/config.go:42 +0x673
main.main()
	v2ray.com/core/infra/control/main/main.go:35 +0x217 > exit status 2
```
You may get panic log using command `journalctl -u v2ray` if your system is Linux (systemd).

4) Please attach your configuration file (**Mask IP addresses before submit this issue**).

```javascript
    // Please attach your configuration here.
{
  "log" : {                                 
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "listen":""
      "port": ,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "",
            "level": 1,
            "alterId": 64
          }
        ]
      }
    }
  ],

  "outbounds": [
    {
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "",
          "headers": {
            "host": ""
          }
        },
        "tlsSettings": {
          "allowInsecure": false
        },
        "security": "tls",
        "network": "ws"
      },
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": ,
            "users": [
                {"id": ""}
            ]
          }
        ]
      }
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    },

    {
      "protocol": "freedom",
      "tag": "direct",
      "settings": {}
    }
  ],

  "routing": {
   "domainStrategy": "IPOnDemand",
    "strategy": "rules",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      },

      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct"
      }
    ]
  }
}
```

Please review your issue before submitting.

**Comment by kslr** [comment]
panic: open config.json: no such file or directory
