### ISSUE TITLE
v2ray极低频率panic

### ISSUE THREAD

**Issue by xsm1997** [v2ray/v2ray-core#2659]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v4.26.0
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
尚不明确（未找到规律），有的时候是下载或看视频，有的时候无大流量。发生频率极低（大概一周一次）
3) Please attach full panic log.

You may get panic log using command `journalctl -u v2ray` if your system is Linux (systemd).

```
Aug 01 15:19:19 vultr.guest v2ray[22205]: panic: extending out of bound
Aug 01 15:19:19 vultr.guest v2ray[22205]: goroutine 1337795 [running]:
Aug 01 15:19:19 vultr.guest v2ray[22205]: v2ray.com/core/common/buf.(*Buffer).Extend(...)
Aug 01 15:19:19 vultr.guest v2ray[22205]:         v2ray.com/core/common/buf/buffer.go:62
Aug 01 15:19:19 vultr.guest v2ray[22205]: v2ray.com/core/common/crypto.(*AuthenticationWriter).seal(0xc0008cf5e0, 0xc000142000, 0x800, 0x800, 0x0, 0x1, 0x1)
Aug 01 15:19:19 vultr.guest v2ray[22205]:         v2ray.com/core/common/crypto/auth.go:258 +0x56c
Aug 01 15:19:19 vultr.guest v2ray[22205]: v2ray.com/core/common/crypto.(*AuthenticationWriter).writePacket(0xc0008cf5e0, 0xc000b8d448, 0x1, 0x1, 0x0, 0x0)
Aug 01 15:19:19 vultr.guest v2ray[22205]:         v2ray.com/core/common/crypto/auth.go:316 +0x166
Aug 01 15:19:19 vultr.guest v2ray[22205]: v2ray.com/core/common/crypto.(*AuthenticationWriter).WriteMultiBuffer(0xc0008cf5e0, 0xc000b8d448, 0x1, 0x1, 0x0, 0x0)
Aug 01 15:19:19 vultr.guest v2ray[22205]:         v2ray.com/core/common/crypto/auth.go:343 +0xc5
Aug 01 15:19:19 vultr.guest v2ray[22205]: v2ray.com/core/proxy/vmess/inbound.transferResponse(0xefdc60, 0xc000a6fad0, 0xc000a6c850, 0xc000a6fa40, 0xc000046740, 0xefe8a0, 0xc000b8d010, 0xc000a6fb90, 0xefcc60, 0xc0006e51c0)
Aug 01 15:19:19 vultr.guest v2ray[22205]:         v2ray.com/core/proxy/vmess/inbound/inbound.go:192 +0xe4
Aug 01 15:19:19 vultr.guest v2ray[22205]: v2ray.com/core/proxy/vmess/inbound.(*Handler).Process.func2(0x0, 0x0)
Aug 01 15:19:19 vultr.guest v2ray[22205]:         v2ray.com/core/proxy/vmess/inbound/inbound.go:304 +0x31d
Aug 01 15:19:19 vultr.guest v2ray[22205]: v2ray.com/core/common/task.Run.func1(0xc000b8d020, 0xc000a679e0, 0xc000a7da00)
Aug 01 15:19:19 vultr.guest v2ray[22205]:         v2ray.com/core/common/task/task.go:28 +0x2b
Aug 01 15:19:19 vultr.guest v2ray[22205]: created by v2ray.com/core/common/task.Run
Aug 01 15:19:19 vultr.guest v2ray[22205]:         v2ray.com/core/common/task/task.go:27 +0xd7
Aug 01 15:19:19 vultr.guest systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

4) Please attach your configuration file (**Mask IP addresses before submit this issue**).

```javascript
{
        "log": {
                "access": "/var/log/v2ray/access.log",
                "error": "/var/log/v2ray/error.log",
                "loglevel": "warning"
        },
        "inbounds": [
                {
                        "port": xxxx,
                        "listen": "127.0.0.1",
                        "protocol": "vmess",
                        "settings": {
                                "clients": [
                                {
                                        "_comment": "aaaa",
                                        "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                        "level": 1,
                                        "email": "aaaa@t.tt",
                                        "alterId": 0
                                },
								......(ignored)......
                                ]
                        },
                        "streamSettings": {
                                "network": "ds",
                                "dsSettings": {
                                     "path": "/var/lib/haproxy/v2ray/v2ray.sock"
                                }
                        }
                }
        ],
        "outbounds": [{
                        "protocol": "freedom",
                        "settings": {
                        }
                }
        ],
        "routing": {
                "domainStrategy": "IPIfNonMatch",
                "rules": [
                        
                ]
        },
        "dns": {
                "servers": [
                        "localhost"
                ]
        }
}
```

（精简了配置）

可能是由于/common/crypto/auth.go的256-261行的seal函数中，eb进行了两次Extend，而前面没有进行检查（只检查了totalSize），导致panic。是不是应该略微增大buffer的capacity？
但是是不是正常情况下就有将近2000bytes的包，我就不知道了，请开发人员查看这个问题。

Please review your issue before submitting.

**Comment by iochen** [comment]
similar issue: #2649

**Comment by lizkes** [comment]
同样的错误
```log
panic: extending out of bound

goroutine 39623 [running]:
v2ray.com/core/common/buf.(*Buffer).Extend(...)
        v2ray-core/common/buf/buffer.go:62
v2ray.com/core/common/buf.SplitSize(0xc00afb36e8, 0x1, 0x1, 0x2000, 0xc00411fc88, 0xbf8242, 0xc00589a7e0, 0xc000166a60, 0xc00411fce0, 0xae40d1)
        v2ray-core/common/buf/multi_buffer.go:180 +0x51e
v2ray.com/core/common/buf.(*BufferedReader).ReadAtMost(0xc0051dcde0, 0x2000, 0x0, 0x0, 0xc00411fd50, 0xaee7d3, 0xc008deb130)
        v2ray-core/common/buf/reader.go:109 +0xa6
v2ray.com/core/common/crypto.(*ChunkStreamReader).ReadMultiBuffer(0xc000d393c0, 0xc00afb36f0, 0x1, 0x1, 0x0, 0x0)
        v2ray-core/common/crypto/chunk.go:120 +0x8e
v2ray.com/core/common/buf.copyInternal(0x11b80c0, 0xc000d393c0, 0x11b9120, 0xc0059a4400, 0xc00589a820, 0x1, 0xc00589a800)
        v2ray-core/common/buf/copy.go:81 +0x50
v2ray.com/core/common/buf.Copy(0x11b80c0, 0xc000d393c0, 0x11b9120, 0xc0059a4400, 0xc000e35f30, 0x1, 0x1, 0xc0001c5340, 0x11d0da0)
        v2ray-core/common/buf/copy.go:104 +0xaf
v2ray.com/core/proxy/vmess/outbound.(*Handler).Process.func3(0x0, 0x0)
        v2ray-core/proxy/vmess/outbound/outbound.go:173 +0x3c3
v2ray.com/core/common/task.OnSuccess.func1(0xc00198b7b0, 0x301080035)
        v2ray-core/common/task/task.go:12 +0x36
v2ray.com/core/common/task.Run.func1(0xc005628b18, 0xc00578e480, 0xc0051f8a20)
        v2ray-core/common/task/task.go:28 +0x32
created by v2ray.com/core/common/task.Run
        v2ray-core/common/task/task.go:27 +0xde
```
只在UDP包通过vmess协议传输时重现。
判断是数据超过默认缓存大小：2048byte了。
我是将v2ray-core/common/buf/buffer.go的第十二行Size改成4096了，可以暂时缓解这个问题。
希望开发者能够解决这个问题。

**Comment by fbion** [comment]
mark

**Comment by rprx** [comment]
简单看了看，代码中存在明显的逻辑 BUG，这个提交应该解决了问题 https://github.com/v2fly/v2ray-core/commit/e425876afe56564e82a528661438aa95857632a7

**Comment by rprx** [comment]
https://github.com/v2fly/V2FlyBleedingEdgeBinary/releases/tag/unstable-e425876afe56564e82a528661438aa95857632a7

试试这个

**Comment by johnwigley** [comment]
> https://github.com/v2fly/V2FlyBleedingEdgeBinary/releases/tag/unstable-e425876afe56564e82a528661438aa95857632a7
> 
> 试试这个

Just tried it and still crashes for me, IF you open large numbers of TCP connections in parallel. I tested it using 40 TCP connections with Iperf3:

iperf3 -c 127.0.0.1 -p 3001 -R -P 40

Iperf3 is connecting to dokodemo-door port forward between client and server v2ray.

It seems to be crashing without generating any logs now, I will try and get a proper crash log and paste it here.

Thanks for trying to fix it!

**Comment by kslr** [comment]
fixed
