### ISSUE TITLE
使用WebSocket 传输方式时，能否自定义非path路径的HTTP状态码与回复内容

### ISSUE THREAD

**Issue by QGB** [v2ray/v2ray-core#2885]
```
./v2ray-linux-64/v2ray --version
V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
A unified platform for anti-censorship.
```

```
"streamSettings": {
      // 指定底层传输方式为 WebSocket
      "network": "ws",
      "wsSettings": {
        // 在哪个路径上提供 WS 服务，可自定义
        "path": "/aaa",
         "​headers": { "Host": "v2ray.com" } //这里只能修改响应头
      }
    }
```
现在 curl 非 aaa路径时，发现响应码都是 :
```
HTTP/1.1 404 Not Found
Date: Wed, 02 Jun 2021 14:16:13 GMT
Content-Length: 0
```
 现在的问题是能否自定义这个响应，比如改成200 OK。我知道通过其他http服务器可以反向代理修改。但是有时系统资源限制只能运行一个v2ray

**Comment by QGB** [comment]
我好像找到相关代码了 https://github.com/v2ray/v2ray-core/blob/5dffca84234a74da9e8174f1e0b0af3dfb2a58ce/transport/internet/websocket/hub.go#L39 改这里就可以，对吗？

**Comment by kslr** [comment]
yes

**Comment by QGB** [comment]
@kslr 
编译成功 v2ray 这个执行文件后替换原来的 出错：
```
./v2ray-linux-64/v2ray -c ./config.json   
V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.3 linux/amd64)
A unified platform for anti-censorship.
2021/06/04 05:25:06 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  ./config.json
panic: crypto/hmac: hash generation function does not produce unique values

goroutine 1 [running]:
crypto/hmac.New(0xc000241558, 0xc00003a6a8, 0x16, 0x18, 0x16, 0x18)
        crypto/hmac/hmac.go:143 +0x370
v2ray.com/core/proxy/vmess/aead.KDF(0xc0005f63a0, 0x10, 0x10, 0xc0002415c0, 0x1, 0x1, 0x40fb98, 0x10, 0xcb7800)
        v2ray.com/core/proxy/vmess/aead/kdf.go:15 +0x12f
v2ray.com/core/proxy/vmess/aead.KDF16(...)
        v2ray.com/core/proxy/vmess/aead/kdf.go:24
v2ray.com/core/proxy/vmess/aead.NewCipherFromKey(0xc0005f63a0, 0x10, 0x10, 0x0, 0x0)
        v2ray.com/core/proxy/vmess/aead/authid.go:35 +0x7c
v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoder(...)
        v2ray.com/core/proxy/vmess/aead/authid.go:47
v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoderItem(...)
        v2ray.com/core/proxy/vmess/aead/authid.go:78
v2ray.com/core/proxy/vmess/aead.(*AuthIDDecoderHolder).AddUser(0xc0003b0640, 0xc00efdb18dd6b51e, 0xf5704a4e42261819, 0xc98f00, 0xc0003ab830)
        v2ray.com/core/proxy/vmess/aead/authid.go:84 +0x59
v2ray.com/core/proxy/vmess.(*TimedUserValidator).Add(0xc00033f340, 0xc0003ab830, 0x0, 0x0)
        v2ray.com/core/proxy/vmess/validator.go:152 +0x1fc
v2ray.com/core/proxy/vmess/inbound.(*Handler).AddUser(0xc0003a9a90, 0xf3c140, 0xc0003aa360, 0xc0003ab830, 0xc0003287c0, 0xdd79dd75d3883e7f)
        v2ray.com/core/proxy/vmess/inbound/inbound.go:166 +0x45
v2ray.com/core/proxy/vmess/inbound.New(0xf3c140, 0xc0003aa360, 0xc000315860, 0xc50000c0000321b0, 0x2, 0xc00028eed0)
        v2ray.com/core/proxy/vmess/inbound/inbound.go:133 +0x3c5
v2ray.com/core/proxy/vmess/inbound.init.1.func1(0xf3c140, 0xc0003aa360, 0xdb09c0, 0xc000315860, 0xf46c01, 0xc000315860, 0x7fce34992501, 0x0)
        v2ray.com/core/proxy/vmess/inbound/inbound.go:355 +0x54
v2ray.com/core/common.CreateObject(0xf3c140, 0xc0003aa360, 0xdb09c0, 0xc000315860, 0x0, 0xf46ca0, 0xc000315860, 0xc00034c060)
        v2ray.com/core/common/type.go:32 +0x22d
v2ray.com/core/app/proxyman/inbound.NewAlwaysOnInboundHandler(0xf3c140, 0xc0003aa360, 0x0, 0x0, 0xc00033ebd0, 0xdb09c0, 0xc000315860, 0x203000, 0xceeec0, 0x0)
        v2ray.com/core/app/proxyman/inbound/always.go:52 +0x6a
v2ray.com/core/app/proxyman/inbound.NewHandler(0xf3c140, 0xc0003aa360, 0xc000322410, 0xb1b5380988308301, 0xb1007fce36217b00, 0x0, 0xc00028f3b0)
        v2ray.com/core/app/proxyman/inbound/inbound.go:162 +0x150
v2ray.com/core/app/proxyman/inbound.init.0.func2(0xf3c140, 0xc0003aa360, 0xd972c0, 0xc000322410, 0xc000239b01, 0x40fb98, 0x30, 0xda1180)
        v2ray.com/core/app/proxyman/inbound/inbound.go:176 +0x54
v2ray.com/core/common.CreateObject(0xf3c140, 0xc0003aa360, 0xd972c0, 0xc000322410, 0xd60a40, 0xc000322f00, 0xf3c140, 0xc0003aa360)
        v2ray.com/core/common/type.go:32 +0x22d
v2ray.com/core.CreateObject(0xc000322f00, 0xd972c0, 0xc000322410, 0x7fce3499dda8, 0xc0003287c0, 0x1, 0x0)
        v2ray.com/core/functions.go:21 +0x55
v2ray.com/core.AddInboundHandler(0xc000322f00, 0xc000322410, 0x4, 0xcf5900)
        v2ray.com/core/v2ray.go:101 +0xa5
v2ray.com/core.addInboundHandlers(0xc000322f00, 0xc000338078, 0x1, 0x1, 0x0, 0x1)
        v2ray.com/core/v2ray.go:117 +0x56
v2ray.com/core.initInstanceWithConfig(0xc000320000, 0xc000322f00, 0x0, 0x0, 0xcd0501)
        v2ray.com/core/v2ray.go:229 +0x455
v2ray.com/core.New(0xc000320000, 0x4, 0x7ffeb966c3fd, 0xd)
        v2ray.com/core/v2ray.go:164 +0x77
main.startV2Ray(0xc00018c240, 0xc0000320a0, 0x2, 0x2)
        v2ray.com/core/main/main.go:121 +0x318
main.main()
        v2ray.com/core/main/main.go:146 +0xb1
```

**Comment by QGB** [comment]
换 `go version go1.15.6 linux/amd64`  编译 运行成功

```
func (h *requestHandler) ServeHTTP(writer http.ResponseWriter, request *http.Request) {
	if request.URL.Path != h.path {
		//writer.WriteHeader(http.StatusNotFound)
              writer.WriteHeader(200)
              fmt.Fprintf(writer, "%#v\n", request.URL)
	      return
	}
```

**Comment by kslr** [comment]
看仓库 readme 已经不更新了

**Comment by xiaokangwang** [comment]
请将修改建以提交到 https://github.com/v2fly/v2ray-core/
