### ISSUE TITLE
v2ray 4.34.0-5 in ubuntu22.04 bug

### ISSUE THREAD

**Issue by gipsyh** [v2ray/v2ray-core#3005]
```
root@ubuntu22:~# v2ray -c /etc/v2ray/config.json 
V2Ray 4.34.0 (user) 20220118-150717 (go1.17.3 linux/arm64)
A unified platform for anti-censorship.
2022/05/01 02:57:44 [Info] v2ray.com/core/main/jsonem: Reading config: /etc/v2ray/config.json
panic: crypto/hmac: hash generation function does not produce unique values

goroutine 1 [running]:
crypto/hmac.New(0x40003eb4a8, {0x4000038090, 0x16, 0x18})
	crypto/hmac/hmac.go:143 +0x338
v2ray.com/core/proxy/vmess/aead.KDF({0x40001fab70, 0x10, 0x10}, {0x40003eb518, 0x1, 0x1})
	v2ray.com/core/proxy/vmess/aead/kdf.go:13 +0x178
v2ray.com/core/proxy/vmess/aead.KDF16(...)
	v2ray.com/core/proxy/vmess/aead/kdf.go:22
v2ray.com/core/proxy/vmess/aead.NewCipherFromKey({0x40001fab70, 0x10, 0x10})
	v2ray.com/core/proxy/vmess/aead/authid.go:41 +0x64
v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoder(...)
	v2ray.com/core/proxy/vmess/aead/authid.go:53
v2ray.com/core/proxy/vmess/aead.NewAuthIDDecoderItem(...)
	v2ray.com/core/proxy/vmess/aead/authid.go:84
v2ray.com/core/proxy/vmess/aead.(*AuthIDDecoderHolder).AddUser(0x40001fc6b0, {0xd1, 0x83, 0xf8, 0x42, 0xa0, 0xac, 0x1, 0x84, 0x8c, ...}, ...)
	v2ray.com/core/proxy/vmess/aead/authid.go:90 +0x54
v2ray.com/core/proxy/vmess.(*TimedUserValidator).Add(0x4000200e00, 0x40001f1b60)
	v2ray.com/core/proxy/vmess/validator.go:152 +0x398
v2ray.com/core/proxy/vmess/inbound.(*Handler).AddUser(0x4000093f90, {0xd462c0, 0x40001f17d0}, 0x40001f1b60)
	v2ray.com/core/proxy/vmess/inbound/inbound.go:166 +0x60
v2ray.com/core/proxy/vmess/inbound.New({0xd462c0, 0x40001f17d0}, 0x40000938b0)
	v2ray.com/core/proxy/vmess/inbound/inbound.go:133 +0x3cc
v2ray.com/core/proxy/vmess/inbound.init.2.func1({0xd462c0, 0x40001f17d0}, {0xbf8b40, 0x40000938b0})
	v2ray.com/core/proxy/vmess/inbound/inbound.go:355 +0x4c
v2ray.com/core/common.CreateObject({0xd462c0, 0x40001f17d0}, {0xbf8b40, 0x40000938b0})
	v2ray.com/core/common/type.go:32 +0x1ec
v2ray.com/core/app/proxyman/inbound.NewAlwaysOnInboundHandler({0xd462c0, 0x40001f17d0}, {0x0, 0x0}, 0x4000200d90, {0xbf8b40, 0x40000938b0})
	v2ray.com/core/app/proxyman/inbound/always.go:52 +0x48
v2ray.com/core/app/proxyman/inbound.NewHandler({0xd462c0, 0x40001f17d0}, 0x40002020c0)
	v2ray.com/core/app/proxyman/inbound/inbound.go:162 +0x304
v2ray.com/core/app/proxyman/inbound.init.0.func2({0xd462c0, 0x40001f17d0}, {0xbeb560, 0x40002020c0})
	v2ray.com/core/app/proxyman/inbound/inbound.go:176 +0x4c
v2ray.com/core/common.CreateObject({0xd462c0, 0x40001f17d0}, {0xbeb560, 0x40002020c0})
	v2ray.com/core/common/type.go:32 +0x1ec
v2ray.com/core.CreateObject(0x4000093360, {0xbeb560, 0x40002020c0})
	v2ray.com/core/functions.go:21 +0x90
v2ray.com/core.AddInboundHandler(0x4000093360, 0x40002020c0)
	v2ray.com/core/v2ray.go:101 +0x80
v2ray.com/core.addInboundHandlers(0x4000093360, {0x4000010fd0, 0x1, 0x1})
	v2ray.com/core/v2ray.go:117 +0x54
v2ray.com/core.initInstanceWithConfig(0x40001f3170, 0x4000093360)
	v2ray.com/core/v2ray.go:229 +0x43c
v2ray.com/core.New(0x40001f3170)
	v2ray.com/core/v2ray.go:164 +0x88
main.startV2Ray()
	v2ray.com/core/main/main.go:115 +0x2c4
main.main()
	v2ray.com/core/main/main.go:139 +0xac
```

**Comment by crb912** [comment]
Did you install `V2Ray` via the "sudo apt install v2ray" command?I think this `V2Ray 4.34.0` version is **NOT** stable. 

When I downgraded to `V2Ray 4.28.2`, the problem was solved.
https://github.com/v2ray/v2ray-core/releases/v4.28.2
