### ISSUE TITLE
cannot cannect to any website with v2ray

### ISSUE THREAD

**Issue by Dig1389** [v2ray/v2ray-core#3290]
hi i want to connect to youtube with my v2ray but when i set system proxy 
the firefox eror"the proxy server is refusing to connect" shows up
here is the log
 2024-04-21 08:50:25.6234-INFO v2rayN start up | v2rayN - V6.43 - 2024/04/09 | C:\Users\sepehr\Desktop\v2rayN-With-Core\v2rayN.exe
2024-04-21 08:51:17.7984-INFO MyAppExit Begin
2024-04-21 08:51:18.1124-INFO MyAppExit End
2024-04-21 08:51:18.1634-INFO OnExit
2024-04-21 08:51:19.3235-INFO v2rayN start up | v2rayN - V6.43 - 2024/04/09 | C:\Users\sepehr\Desktop\v2rayN-With-Core\v2rayN.exe
2024-04-21 08:52:02.7120-DEBUG Base64Decode,The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
2024-04-21 08:52:02.7530-DEBUG    at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at v2rayN.Utils.Base64Decode(String plainText)
2024-04-21 08:52:20.6440-INFO UpdateTaskRunSubscription
2024-04-21 08:52:23.6732-DEBUG Base64Decode,The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
2024-04-21 08:52:23.6732-DEBUG    at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at v2rayN.Utils.Base64Decode(String plainText)
2024-04-21 08:52:59.6522-INFO MyAppExit Begin
2024-04-21 08:52:59.7912-INFO MyAppExit End
2024-04-21 08:52:59.8312-INFO OnExit
2024-04-21 08:53:01.0163-INFO v2rayN start up | v2rayN - V6.43 - 2024/04/09 | C:\Users\sepehr\Desktop\v2rayN-With-Core\v2rayN.exe
2024-04-21 08:54:03.2619-INFO UpdateTaskRunSubscription
2024-04-21 08:55:03.2753-INFO UpdateTaskRunGeo
2024-04-21 08:57:20.6002-INFO MyAppExit Begin
2024-04-21 08:57:20.7362-INFO MyAppExit End
2024-04-21 08:57:20.7492-INFO OnExit
2024-04-21 08:57:42.5286-INFO v2rayN start up | v2rayN - V6.43 - 2024/04/09 | C:\Users\sepehr\Desktop\v2rayN-With-Core\v2rayN.exe
2024-04-21 08:58:14.2442-INFO MyAppExit Begin
2024-04-21 08:58:14.3472-INFO MyAppExit End
2024-04-21 08:58:14.3662-INFO OnExit
2024-04-21 08:58:18.1694-INFO v2rayN start up | v2rayN - V6.43 - 2024/04/09 | C:\Users\sepehr\Desktop\v2rayN-With-Core\v2rayN.exe
2024-04-21 08:58:44.9201-DEBUG Base64Decode,The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
2024-04-21 08:58:44.9661-DEBUG    at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at v2rayN.Utils.Base64Decode(String plainText)
2024-04-21 08:59:33.3319-INFO UpdateTaskRunSubscription
2024-04-21 09:00:33.3283-INFO UpdateTaskRunGeo
2024-04-21 09:02:07.2847-INFO MyAppExit Begin
2024-04-21 09:02:07.4477-INFO MyAppExit End
2024-04-21 09:02:07.4877-INFO OnExit
2024-04-21 09:02:31.0151-INFO v2rayN start up | v2rayN - V6.43 - 2024/04/09 | C:\Users\sepehr\Desktop\v2rayN-With-Core\v2rayN.exe
2024-04-21 09:02:46.2800-INFO MyAppExit Begin
2024-04-21 09:02:46.4940-INFO MyAppExit End
2024-04-21 09:02:46.5660-INFO OnExit
2024-04-21 09:02:48.2571-INFO v2rayN start up | v2rayN - V6.43 - 2024/04/09 | C:\Users\sepehr\Desktop\v2rayN-With-Core\v2rayN.exe
2024-04-21 09:03:50.1716-INFO UpdateTaskRunSubscription
2024-04-21 09:04:04.6054-DEBUG Invalid URI: The hostname could not be parsed.,Invalid URI: The hostname could not be parsed.
2024-04-21 09:04:04.6444-DEBUG    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at v2rayN.Handler.ShareHandler.ResolveTrojan(String result)
   at v2rayN.Handler.ShareHandler.ImportFromClipboardConfig(String clipboardData, String& msg)
2024-04-21 09:04:05.5915-DEBUG ,
2024-04-21 09:04:05.5915-DEBUG    at v2rayN.Handler.CoreHandler.RunProcess(ProfileItem node, CoreInfo coreInfo, String configPath, Boolean displayLog)
2024-04-21 09:04:32.0420-DEBUG Exception 0xc0000005 0x0 0x0 0x0
PC=0x0
runtime.asmstdcall(0x22fcf8)
	runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47a9da
rax     0x0
rbx     0x1d9fcb8
rcx     0x1e2a1c8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x1fea2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x1d9e540
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
,Exception 0xc0000005 0x0 0x0 0x0
PC=0x0
runtime.asmstdcall(0x22fcf8)
	runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47a9da
rax     0x0
rbx     0x1d9fcb8
rcx     0x1e2a1c8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x1fea2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x1d9e540
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

2024-04-21 09:04:32.0420-DEBUG    at v2rayN.Handler.CoreHandler.RunProcess(ProfileItem node, CoreInfo coreInfo, String configPath, Boolean displayLog)
2024-04-21 09:04:50.1040-INFO UpdateTaskRunGeo
2024-04-21 09:05:52.3751-DEBUG ,
2024-04-21 09:05:52.3751-DEBUG    at v2rayN.Handler.CoreHandler.RunProcess(ProfileItem node, CoreInfo coreInfo, String configPath, Boolean displayLog)
2024-04-21 09:06:29.0452-DEBUG ,
2024-04-21 09:06:29.0452-DEBUG    at v2rayN.Handler.CoreHandler.RunProcess(ProfileItem node, CoreInfo coreInfo, String configPath, Boolean displayLog)
2024-04-21 09:12:38.8003-INFO MyAppExit Begin
2024-04-21 09:12:38.8673-INFO MyAppExit End
2024-04-21 09:12:38.9243-INFO OnExit

**Comment by highlander0test** [comment]
刚用v2ray搭建的，大家可以体验一下
欢迎体验
本网站处于推广阶段，联系群主，注册后提供邮箱，提供免费1个月体验机会
官网：https://www.bzg.life/
官群：https://t.me/BZG_group
