### ISSUE TITLE
v2.16.x 使用 socks inbound 的时候引起程序崩溃

### ISSUE THREAD

**Issue by XGHeaven** [v2ray/v2ray-core#379]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
server: 尝试了 v2.16.x 的所有版本
client: telegram 的 socks 代理

2)  你的使用场景是什么？
用 telegram socks 代理，就这么简单

3)  你看到的不正常的现象是什么？
    在 v2.15的版本的时候，socks 代理没有什么问题。但是当我更新到 v2.16 版本的时候，出现了崩溃的情况。简单来说：
* v2.16 根本无法运行。一运行直接报错。报错如下
```
[root@li1591-154 ~]# /usr/bin/v2ray/v2ray -version
V2Ray v2.16 (One for all) 20170127
An unified platform for anti-censorship.
[root@li1591-154 ~]# /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
V2Ray v2.16 (One for all) 20170127
An unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x557b0a]

goroutine 1 [running]:
panic(0x7e1b80, 0xc42000e090)
	/home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x1a1
v2ray.com/core/transport/internet/tcp.ListenTCP(0x0, 0x0, 0xc400002124, 0x0, 0xc41ff4e100, 0xc4214d5c20, 0x40f7be, 0xc42163db40, 0x10)
	/home/travis/gopath/src/v2ray.com/core/transport/internet/tcp/hub.go:39 +0x3a
v2ray.com/core/transport/internet.ListenTCP(0x0, 0x0, 0xa32124, 0xc42163db40, 0x0, 0xc4214ee480, 0xa647a0, 0xc4214d5ce8)
	/home/travis/gopath/src/v2ray.com/core/transport/internet/tcp_hub.go:53 +0xb4
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).Start(0xc4214fb2d0, 0x7f4b2480c2f0, 0x0)
	/home/travis/gopath/src/v2ray.com/core/app/proxyman/inbound/worker.go:66 +0xed
v2ray.com/core/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0xc421506210, 0xc4214d9840, 0xc4214d5d20)
	/home/travis/gopath/src/v2ray.com/core/app/proxyman/inbound/always.go:62 +0x55
v2ray.com/core/app/proxyman/inbound.(*DefaultInboundHandlerManager).Start(0xc4214d9840, 0xc4214ebf20, 0x7f4b2480c2f0)
	/home/travis/gopath/src/v2ray.com/core/app/proxyman/inbound/inbound.go:73 +0x54
v2ray.com/core.(*Point).Start(0xc4214f0fe0, 0xc4214f0fe0, 0x0)
	/home/travis/gopath/src/v2ray.com/core/v2ray.go:124 +0x4f
main.startV2Ray(0x0)
	/home/travis/gopath/src/v2ray.com/core/main/main.go:81 +0x606
main.main()
	/home/travis/gopath/src/v2ray.com/core/main/main.go:99 +0x45
```
* v2.16.1-4 可以运行，正常接收 ss 代理，但是一旦使用 socks 代理，程序就崩溃，错误如下

`v2.16.1`
```
[root@li1591-154 ~]# /usr/bin/v2ray/v2ray -version
V2Ray v2.16.1 (One for all) 20170127
An unified platform for anti-censorship.
[root@li1591-154 ~]# /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
V2Ray v2.16.1 (One for all) 20170127
An unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4abf46]

goroutine 21 [running]:
panic(0x7e1b80, 0xc42000e090)
	/home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x1a1
v2ray.com/core/common/net.Destination.NetAddr(0x100000000000000, 0x0, 0x0, 0x6b5, 0x0)
	/home/travis/gopath/src/v2ray.com/core/common/net/destination.go:44 +0x26
v2ray.com/core/common/net.Destination.String(0x0, 0x0, 0x0, 0x82f6c0, 0xc421518e01)
	/home/travis/gopath/src/v2ray.com/core/common/net/destination.go:48 +0x6c
v2ray.com/core/common/net.(*Destination).String(0xc421518f40, 0x82f6c0, 0xc421518f40)
	<autogenerated>:34 +0x6b
v2ray.com/core/common/serial.ToString(0x82f6c0, 0xc421518f40, 0xc420034c50, 0x40f7be)
	/home/travis/gopath/src/v2ray.com/core/common/serial/string.go:19 +0x11c
v2ray.com/core/common/log/internal.(*AccessLog).String(0xc421677b40, 0xc420034c80, 0x40ffe8)
	/home/travis/gopath/src/v2ray.com/core/common/log/internal/log_entry.go:31 +0x4c
v2ray.com/core/common/log/internal.(*FileLogWriter).Log(0xc4214d9780, 0xa2dfc0, 0xc421677b40)
	/home/travis/gopath/src/v2ray.com/core/common/log/internal/log_writer.go:54 +0x3e
v2ray.com/core/common/log.Access(0x82f6c0, 0xc421518f40, 0x82f6c0, 0xc421518f60, 0x85e2c5, 0x8, 0x7c26e0, 0xc42167d8d0)
	/home/travis/gopath/src/v2ray.com/core/common/log/access.go:37 +0xdf
v2ray.com/core/proxy/socks.(*Server).processTCP(0xc4214d9ba0, 0xa33f00, 0xc4215077a0, 0xa37d80, 0xc4214f96c0, 0xc421518da0, 0xa33f00)
	/home/travis/gopath/src/v2ray.com/core/proxy/socks/server.go:94 +0x68d
v2ray.com/core/proxy/socks.(*Server).Process(0xc4214d9ba0, 0xa33f00, 0xc4215077a0, 0x2, 0xa37d80, 0xc4214f96c0, 0xc4215077a0, 0x1)
	/home/travis/gopath/src/v2ray.com/core/proxy/socks/server.go:63 +0x1d3
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).callback(0xc4214f9340, 0xa37d80, 0xc4214f96c0)
	/home/travis/gopath/src/v2ray.com/core/app/proxyman/inbound/worker.go:53 +0x115
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).(v2ray.com/core/app/proxyman/inbound.callback)-fm(0xa37d80, 0xc4214f96c0)
	/home/travis/gopath/src/v2ray.com/core/app/proxyman/inbound/worker.go:66 +0x3e
created by v2ray.com/core/transport/internet.(*TCPHub).start
	/home/travis/gopath/src/v2ray.com/core/transport/internet/tcp_hub.go:91 +0x157
```
`v2.16.2`
```
[root@li1591-154 ~]# /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
V2Ray v2.16.2 (One for all) 20170128
An unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4abf06]

goroutine 21 [running]:
panic(0x7e1a20, 0xc42000e090)
	/home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x1a1
v2ray.com/core/common/net.Destination.NetAddr(0x100000000000000, 0x0, 0x0, 0x6b5, 0x0)
	/home/travis/gopath/src/v2ray.com/core/common/net/destination.go:44 +0x26
v2ray.com/core/common/net.Destination.String(0x0, 0x0, 0x0, 0x82f560, 0xc421518b01)
	/home/travis/gopath/src/v2ray.com/core/common/net/destination.go:48 +0x6c
v2ray.com/core/common/net.(*Destination).String(0xc421518cc0, 0x82f560, 0xc421518cc0)
	<autogenerated>:34 +0x6b
v2ray.com/core/common/serial.ToString(0x82f560, 0xc421518cc0, 0xc420034c50, 0x40f7be)
	/home/travis/gopath/src/v2ray.com/core/common/serial/string.go:19 +0x11c
v2ray.com/core/common/log/internal.(*AccessLog).String(0xc4215a9500, 0xc420034c80, 0x40ffe8)
	/home/travis/gopath/src/v2ray.com/core/common/log/internal/log_entry.go:31 +0x4c
v2ray.com/core/common/log/internal.(*FileLogWriter).Log(0xc4214d97a0, 0xa2dfc0, 0xc4215a9500)
	/home/travis/gopath/src/v2ray.com/core/common/log/internal/log_writer.go:54 +0x3e
v2ray.com/core/common/log.Access(0x82f560, 0xc421518cc0, 0x82f560, 0xc421518ce0, 0x85e165, 0x8, 0x7c2640, 0xc42163de20)
	/home/travis/gopath/src/v2ray.com/core/common/log/access.go:37 +0xdf
v2ray.com/core/proxy/socks.(*Server).processTCP(0xc4214d9bc0, 0xa33f00, 0xc4215077a0, 0xa37d80, 0xc4214f96c0, 0xc421518b20, 0xa33f00)
	/home/travis/gopath/src/v2ray.com/core/proxy/socks/server.go:94 +0x68d
v2ray.com/core/proxy/socks.(*Server).Process(0xc4214d9bc0, 0xa33f00, 0xc4215077a0, 0x2, 0xa37d80, 0xc4214f96c0, 0xc4215077a0, 0x1)
	/home/travis/gopath/src/v2ray.com/core/proxy/socks/server.go:63 +0x1d3
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).callback(0xc4214f9340, 0xa37d80, 0xc4214f96c0)
	/home/travis/gopath/src/v2ray.com/core/app/proxyman/inbound/worker.go:53 +0x115
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).(v2ray.com/core/app/proxyman/inbound.callback)-fm(0xa37d80, 0xc4214f96c0)
	/home/travis/gopath/src/v2ray.com/core/app/proxyman/inbound/worker.go:66 +0x3e
created by v2ray.com/core/transport/internet.(*TCPHub).start
	/home/travis/gopath/src/v2ray.com/core/transport/internet/tcp_hub.go:91 +0x157
```
`v2.16.4`
```
[root@li1591-154 ~]# /usr/bin/v2ray/v2ray -version
V2Ray v2.16.4 (One for all) 20170128
An unified platform for anti-censorship.
[root@li1591-154 ~]# /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
V2Ray v2.16.4 (One for all) 20170128
An unified platform for anti-censorship.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4abf06]

goroutine 21 [running]:
panic(0x7e1a20, 0xc42000e090)
	/home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x1a1
v2ray.com/core/common/net.Destination.NetAddr(0x100000000000000, 0x0, 0x0, 0x6b5, 0x0)
	/home/travis/gopath/src/v2ray.com/core/common/net/destination.go:44 +0x26
v2ray.com/core/common/net.Destination.String(0x0, 0x0, 0x0, 0x82f540, 0xc421516a01)
	/home/travis/gopath/src/v2ray.com/core/common/net/destination.go:48 +0x6c
v2ray.com/core/common/net.(*Destination).String(0xc421516b80, 0x82f540, 0xc421516b80)
	<autogenerated>:34 +0x6b
v2ray.com/core/common/serial.ToString(0x82f540, 0xc421516b80, 0xc420034c50, 0x40f7be)
	/home/travis/gopath/src/v2ray.com/core/common/serial/string.go:19 +0x11c
v2ray.com/core/common/log/internal.(*AccessLog).String(0xc4215a72c0, 0xc420034c80, 0x40ffe8)
	/home/travis/gopath/src/v2ray.com/core/common/log/internal/log_entry.go:31 +0x4c
v2ray.com/core/common/log/internal.(*FileLogWriter).Log(0xc4214d9780, 0xa2dfc0, 0xc4215a72c0)
	/home/travis/gopath/src/v2ray.com/core/common/log/internal/log_writer.go:54 +0x3e
v2ray.com/core/common/log.Access(0x82f540, 0xc421516b80, 0x82f540, 0xc421516ba0, 0x85e145, 0x8, 0x7c2640, 0xc42163de10)
	/home/travis/gopath/src/v2ray.com/core/common/log/access.go:37 +0xdf
v2ray.com/core/proxy/socks.(*Server).processTCP(0xc4214d9ba0, 0xa33f00, 0xc4215057a0, 0xa37d80, 0xc4214f96c0, 0xc4215169e0, 0xa33f00)
	/home/travis/gopath/src/v2ray.com/core/proxy/socks/server.go:94 +0x66e
v2ray.com/core/proxy/socks.(*Server).Process(0xc4214d9ba0, 0xa33f00, 0xc4215057a0, 0x2, 0xa37d80, 0xc4214f96c0, 0xc4215057a0, 0x1)
	/home/travis/gopath/src/v2ray.com/core/proxy/socks/server.go:65 +0x1f2
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).callback(0xc4214f9340, 0xa37d80, 0xc4214f96c0)
	/home/travis/gopath/src/v2ray.com/core/app/proxyman/inbound/worker.go:53 +0x115
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).(v2ray.com/core/app/proxyman/inbound.callback)-fm(0xa37d80, 0xc4214f96c0)
	/home/travis/gopath/src/v2ray.com/core/app/proxyman/inbound/worker.go:66 +0x3e
created by v2ray.com/core/transport/internet.(*TCPHub).start
	/home/travis/gopath/src/v2ray.com/core/transport/internet/tcp_hub.go:91 +0x157
```

还有 #364 这个问题，，，，也希望可以解决
4)  你期待看到的正确表现是怎样的？
正确使用。。。

配置文件我就不贴了，因为不可能是配置的问题，因为 v2.15 可以用，但是 v2.16 不能用。。。

**Comment by v2ray** [comment]
已修复，见 2.16.5
