### ISSUE TITLE
2.16.6客户端透明代理报错panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AxisRay** [v2ray/v2ray-core#381]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
2.16.6
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
VPS（server）----GFW----RPi（透明代理）----PC
VMess_TCP+HTTP伪装
3)  你看到的不正常的现象是什么？
    What did you see?
启动报错PANIC

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
    ```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
    ```
    
    Client Configuration File（客户端配置文件）:
    ```javascript
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 3080,
    "listen": "0.0.0.0",
    "protocol": "dokodemo-door",
    "settings": {
      "network": "tcp,udp",
      "timeout": 0,
      "followRedirect": true
    }
  },
  "inboundDetour": [
    {
      "port": 5300,
      "listen": "0.0.0.0",
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.4.4",
        "port": 53,
        "network": "udp",
        "timeout": 0,
        "followRedirect": false
        }
     }
  ],
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "****************",
          "port": 80,
          "users": [
            {
              "id": "*************",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "tcpSettings": {
        "connectionReuse": true,
        "header": {
          "type": "http",
          "request": {
            "version": "1.1",
            "method": "GET",
            "path": ["/proxy","/data","/download"],
            "headers": {
              "Host": ["********", "*********"],
              "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
                "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": ["gzip, deflate"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          },
          "response": {
            "version": "1.1",
            "status": "200",
            "reason": "OK",
            "headers": {
              "Content-Type": ["application/octet-stream", "image/x-portable-bitmap","image/tiff","text/html"],
              "Transfer-Encoding": ["chunked"],
            "Connection": ["keep-alive"],
            "Pragma": "no-cache"
            }
          }
        }
      }
    }
  }
}

    ```
    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
    ```
正常
    ```
    
    Client Log File（客户端日志）:
    ```
Jan 31 18:46:02 raspberrypi systemd[1]: Started V2Ray Service.
Jan 31 18:46:02 raspberrypi v2ray[17138]: V2Ray v2.16.6 (One for all) 20170129
Jan 31 18:46:02 raspberrypi v2ray[17138]: An unified platform for anti-censorship.
Jan 31 18:46:02 raspberrypi v2ray[17138]: 2017/01/31 18:46:02 [Warning]V2Ray started.
Jan 31 18:46:03 raspberrypi v2ray[17138]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 31 18:46:03 raspberrypi v2ray[17138]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2a669c]
Jan 31 18:46:03 raspberrypi v2ray[17138]: goroutine 65 [running]:
Jan 31 18:46:03 raspberrypi v2ray[17138]: panic(0x3fd528, 0x1091c008)
Jan 31 18:46:03 raspberrypi v2ray[17138]: /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x33c
Jan 31 18:46:03 raspberrypi v2ray[17138]: v2ray.com/core/proxy/vmess/encoding.(*ClientSession).EncodeRequestHeader(0x11e06380, 0x11e3e040, 0x5bc190, 0x11de0240)
Jan 31 18:46:03 raspberrypi v2ray[17138]: /home/travis/gopath/src/v2ray.com/core/proxy/vmess/encoding/client.go:87 +0xa04
Jan 31 18:46:03 raspberrypi v2ray[17138]: v2ray.com/core/proxy/vmess/outbound.(*VMessOutboundHandler).Process.func2(0x0, 0x0)
Jan 31 18:46:03 raspberrypi v2ray[17138]: /home/travis/gopath/src/v2ray.com/core/proxy/vmess/outbound/outbound.go:106 +0x1e0
Jan 31 18:46:03 raspberrypi v2ray[17138]: v2ray.com/core/common/signal.executeAndFulfill(0x11e3e8a0, 0x11e063c0)
Jan 31 18:46:03 raspberrypi v2ray[17138]: /home/travis/gopath/src/v2ray.com/core/common/signal/exec.go:8 +0x1c
Jan 31 18:46:03 raspberrypi v2ray[17138]: created by v2ray.com/core/common/signal.ExecuteAsync
Jan 31 18:46:03 raspberrypi v2ray[17138]: /home/travis/gopath/src/v2ray.com/core/common/signal/exec.go:17 +0x58
Jan 31 18:46:03 raspberrypi systemd[1]: v2ray.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 31 18:46:03 raspberrypi systemd[1]: Unit v2ray.service entered failed state.
    ```

**Comment by v2ray** [comment]
会在 2.16.7 修复
