### ISSUE TITLE
TestVMessGCMMux failed in 3.7

### ISSUE THREAD

**Issue by felixonmars** [v2ray/v2ray-core#859]
The following errors appear when running the test suite for 3.7 release:

```
=== RUN   TestVMessGCMMux
V2Ray 3.8 (die Commanderin) Custom
An unified platform for anti-censorship.
V2Ray 3.8 (die Commanderin) Custom
An unified platform for anti-censorship.
2018/02/10 02:23:59 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:41299
2018/02/10 02:23:59 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:41299
2018/02/10 02:23:59 [Warning]: Core: V2Ray started
2018/02/10 02:23:59 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:44973
2018/02/10 02:23:59 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:44973
2018/02/10 02:23:59 [Warning]: Core: V2Ray started
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54116
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54088
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54090
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54092
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54094
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54098
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54096
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54100
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54102
2018/02/10 02:24:01 [Debug]: Proxy|Dokodemo: processing connection from: 127.0.0.1:54104
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Proxyman|Mux: dispatching request to tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Proxyman|Mux: dispatching request to tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Proxyman|Mux: dispatching request to tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Proxyman|Mux: dispatching request to tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:127.0.0.1:44973
2018/02/10 02:24:01 [Info]: Transport|Internet|TCP: dialing TCP to tcp:127.0.0.1:44973
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Dispatcher: default route for tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Proxyman|Mux: dispatching request to tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Proxyman|Mux: dispatching request to tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Proxyman|Mux: dispatching request to tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: Transport|Internet|TCP: dialing TCP to tcp:127.0.0.1:44973
2018/02/10 02:24:01 [Info]: App|Proxyman|Mux: dispatching request to tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: App|Proxyman|Mux: dispatching request to tcp:127.0.0.1:34471
2018/02/10 02:24:01 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:127.0.0.1:44973
2018/02/10 02:24:01 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:127.0.0.1:44973
panic: runtime error: slice bounds out of range

goroutine 179 [running]:
v2ray.com/core/common/buf.(*Buffer).Read(...)
        /build/v2ray/src/build/src/v2ray.com/core/common/buf/buffer.go:165
v2ray.com/core/common/buf.(*MultiBuffer).Read(0xc420390bc0, 0xc4204cb864, 0x79c, 0x7be, 0xc420416d10, 0x720e68, 0x20)
        /build/v2ray/src/build/src/v2ray.com/core/common/buf/multi_buffer.go:86 +0x30b
v2ray.com/core/common/buf.ReadFrom.func1(0xc4204cb842, 0x7be, 0x7be, 0xd128e0, 0xc420390be0, 0xc420390bc0)
        /build/v2ray/src/build/src/v2ray.com/core/common/buf/io.go:31 +0x4d
v2ray.com/core/common/buf.(*Buffer).AppendSupplier(0xc420404340, 0xc420390be0, 0xc420390be0, 0xc420416d00)
        /build/v2ray/src/build/src/v2ray.com/core/common/buf/buffer.go:57 +0x68
v2ray.com/core/common/buf.(*BufferedWriter).WriteMultiBuffer(0xc42041e180, 0xc4205c41c0, 0x1c, 0x38, 0x0, 0x0)
        /build/v2ray/src/build/src/v2ray.com/core/common/buf/writer.go:99 +0x127
v2ray.com/core/common/crypto.(*AuthenticationWriter).writePacket(0xc4202d0200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/v2ray/src/build/src/v2ray.com/core/common/crypto/auth.go:231 +0x1e4
v2ray.com/core/common/crypto.(*AuthenticationWriter).WriteMultiBuffer(0xc4202d0200, 0xc420082800, 0x1c, 0x80, 0x80, 0x0)
        /build/v2ray/src/build/src/v2ray.com/core/common/crypto/auth.go:239 +0x9b
v2ray.com/core/proxy/vmess/outbound.(*Handler).Process.func2(0xc420014af0, 0x0)
        /build/v2ray/src/build/src/v2ray.com/core/proxy/vmess/outbound/outbound.go:122 +0x66b
v2ray.com/core/common/signal.executeAndFulfill(0xc42039c060, 0xc42039c0c0)
        /build/v2ray/src/build/src/v2ray.com/core/common/signal/exec.go:8 +0x27
created by v2ray.com/core/common/signal.ExecuteAsync
        /build/v2ray/src/build/src/v2ray.com/core/common/signal/exec.go:18 +0x67
Unexpected error from readFrom: EOF
2018/02/10 02:24:01 [Info]: App|Proxyman|Inbound: connection ends > Proxy|VMess|Encoding: failed to read request header > EOF
2018/02/10 02:24:01 [Info]: App|Proxyman|Inbound: connection ends > Proxy|VMess|Encoding: failed to read request header > EOF
2018/02/10 02:24:01 [Info]: App|Proxyman|Inbound: connection ends > Proxy|VMess|Encoding: failed to read request header > EOF
2018/02/10 02:24:01 [Info]: App|Proxyman|Inbound: connection ends > Proxy|VMess|Encoding: failed to read request header > EOF
  vmess_test.go:1038: Not true that ([]) equals to ([189 68 194 125 78 164 225 58 164 234 163 186 180 
……
<snip>
rax    0xca
rbx    0x1393800
rcx    0x76d853
rdx    0x0
rdi    0x1393938
rsi    0x0
rbp    0x7ffdc7517da0
rsp    0x7ffdc7517d58
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0xe03555
r14    0xa
r15    0x0
rip    0x76d851
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL    v2ray.com/core/testing/scenarios        600.009s
?       v2ray.com/core/testing/servers/http     [no test files]
?       v2ray.com/core/testing/servers/tcp      [no test files]
?       v2ray.com/core/testing/servers/udp      [no test files]
?       v2ray.com/core/testing/tls      [no test files]
?       v2ray.com/core/transport        [no test files]
```

**Comment by DarienRaymond** [comment]
Fixed in 42d83a703e246755db8a45f53e0296622f7be5e5
