### ISSUE TITLE
传入协议 SS 启动一段时间会终止运行

### ISSUE THREAD

**Issue by liuminglm** [v2ray/v2ray-core#999]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

# 3.14

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

# kitsunebi 科学上网

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

# 传入协议 SS ，启动时可以使用，但是启动一段时间会终止运行

4)  你期待看到的正确表现是怎样的？

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

# {
 "outbound": {
  "streamSettings": null, 
  "tag": null, 
  "protocol": "freedom", 
  "mux": null, 
  "settings": null
 }, 
 "log": {
  "access": "", 
  "loglevel": "", 
  "error": ""
 }, 
 "inboundDetour": null, 

 "inbound": {
  "port": 3535,
  "listen": "0.0.0.0",
  "protocol": "shadowsocks",
  "settings": {
  "method": "aes-256-gcm",
  "password": "××××××",
  "udp": true,
  "level": 1,
  "ota": true
},
  "streamSettings": {},
  "tag": "ss",
  "domainOverride": ["http", "tls"]
},
‘’‘’‘’‘’‘’‘’‘’‘’‘’‘’‘’‘’‘’‘’‘’‘’

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
# panic: runtime error: slice bounds out of range

goroutine 2822 [running]:
v2ray.com/core/common/buf.ReadFullFrom.func1(0xc421a71800, 0x800, 0x800, 0x57227d, 0xa16da0, 0xc4216429c0)
	/v2ray/src/v2ray.com/core/common/buf/io.go:38 +0x82
v2ray.com/core/common/buf.(*Buffer).Reset(0xc420a20e10, 0xc4216429c0, 0x2000, 0xc4216429c0)
	/v2ray/src/v2ray.com/core/common/buf/buffer.go:79 +0x45
v2ray.com/core/common/buf.(*MultiBuffer).SliceBySize(0xc421aeeda0, 0x2000, 0x80, 0x100000000, 0xc421aeede0)
	/v2ray/src/v2ray.com/core/common/buf/multi_buffer.go:171 +0x2f2
v2ray.com/core/app/proxyman/mux.(*Writer).WriteMultiBuffer(0xc4227ae540, 0x0, 0x0, 0x0, 0x0, 0x0)
	/v2ray/src/v2ray.com/core/app/proxyman/mux/writer.go:91 +0x1e4
v2ray.com/core/common/buf.(*copyHandler).writeTo(0xc4202960f0, 0xb0cb20, 0xc4227ae540, 0xc422446400, 0x1, 0x80, 0x0, 0x0)
	/v2ray/src/v2ray.com/core/common/buf/copy.go:30 +0x56
v2ray.com/core/common/buf.copyInternal(0x7f09c4a24c78, 0xc4202265a0, 0xb0cb20, 0xc4227ae540, 0xc4202960f0, 0xc420463ee8, 0x40e7d8)
	/v2ray/src/v2ray.com/core/common/buf/copy.go:91 +0x1aa
v2ray.com/core/common/buf.Copy(0x7f09c4a24c78, 0xc4202265a0, 0xb0cb20, 0xc4227ae540, 0x0, 0x0, 0x0, 0x0, 0x0)
	/v2ray/src/v2ray.com/core/common/buf/copy.go:109 +0xa8
v2ray.com/core/app/proxyman/mux.fetchInput(0xb181c0, 0xc420a20240, 0xc4227ae400, 0x7f09c4a24b40, 0xc421bd50e0)
	/v2ray/src/v2ray.com/core/app/proxyman/mux/mux.go:158 +0x471
created by v2ray.com/core/app/proxyman/mux.(*Client).Dispatch
	/v2ray/src/v2ray.com/core/app/proxyman/mux/mux.go:179 +0x1a0


7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
```
# 2018/03/28 16:22:18 127.0.0.1:54670 accepted tcp:gateway.icloud.com:443 
2018/03/28 16:22:39 127.0.0.1:54674 accepted tcp:api.gamer.com.tw:443 
2018/03/28 16:23:38 127.0.0.1:54686 accepted tcp:api.gamer.com.tw:443 
2018/03/28 16:24:11 127.0.0.1:54698 accepted tcp:e.crashlytics.com:443 
2018/03/28 16:24:11 127.0.0.1:54700 accepted tcp:app-measurement.com:443 
2018/03/28 16:24:14 127.0.0.1:54706 accepted tcp:video.twimg.com:443 
2018/03/28 16:24:14 127.0.0.1:54708 accepted tcp:video.twimg.com:443 
2018/03/28 16:24:14 127.0.0.1:54710 accepted tcp:video.twimg.com:443 
2018/03/28 16:24:14 127.0.0.1:54714 accepted tcp:api.twitter.com:443 
2018/03/28 16:24:14 127.0.0.1:54712 accepted tcp:pbs.twimg.com:443 
2018/03/28 16:24:14 127.0.0.1:54716 accepted tcp:video.twimg.com:443 
2018/03/28 16:24:15 127.0.0.1:54730 accepted tcp:pbs.twimg.com:443 
2018/03/28 16:24:16 127.0.0.1:54734 accepted tcp:video.twimg.com:443 
2018/03/28 16:24:17 127.0.0.1:54738 accepted tcp:video.twimg.com:443 
2018/03/28 16:24:18 127.0.0.1:54742 accepted tcp:video.twimg.com:443 
2018/03/28 16:24:18 127.0.0.1:54746 accepted tcp:video.twimg.com:443 
2018/03/28 16:24:18 127.0.0.1:54748 accepted tcp:video.twimg.com:443 
2018/03/28 16:25:41 127.0.0.1:54774 accepted tcp:video.twimg.com:443 
2018/03/28 16:25:42 127.0.0.1:54778 accepted tcp:video.twimg.com:443 
2018/03/28 16:26:26 127.0.0.1:54786 accepted tcp:video.twimg.com:443 
2018/03/28 16:26:40 127.0.0.1:54798 accepted tcp:video.twimg.com:443 
2018/03/28 16:26:42 127.0.0.1:54802 accepted tcp:video.twimg.com:443 
2018/03/28 16:28:18 127.0.0.1:54816 accepted tcp:init.itunes.apple.com:443 
2018/03/28 16:28:18 127.0.0.1:54818 accepted tcp:su.itunes.apple.com:443 
2018/03/28 16:28:19 127.0.0.1:54824 accepted tcp:xp.apple.com:443 
2018/03/28 16:28:22 127.0.0.1:54828 accepted tcp:xp.apple.com:443 
2018/03/28 16:28:24 127.0.0.1:54832 accepted tcp:web.archive.org:443 
2018/03/28 16:28:25 127.0.0.1:54836 accepted tcp:p42-keyvalueservice.icloud.com:443 
2018/03/28 16:28:30 127.0.0.1:54840 accepted tcp:www.ipip.net:443 
2018/03/28 16:28:30 127.0.0.1:54844 accepted tcp:p42-keyvalueservice.icloud.com:443 
2018/03/28 16:28:31 127.0.0.1:54848 accepted tcp:cdn.ipip.net:443 
2018/03/28 16:28:32 127.0.0.1:54850 accepted tcp:www.ipip.net:443

**Comment by wongsyrone** [comment]
你把 "method": "aes-256-gcm", 换成非AEAD的试试：比如
"aes-256-cfb"
"aes-128-cfb"
"chacha20"
"chacha20-ietf"

**Comment by liuminglm** [comment]
换成非AEAD，用了半个小时，没有断，可能是AEAD有问题

**Comment by wongsyrone** [comment]
和 https://github.com/v2ray/v2ray-core/issues/983 应该是同一个问题
